import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

export default function ContactUs() {

    return(
        <>
        <Head>
          <title>Lumyn | Contact Us</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="page">
            <main className="main contact_us">
            <div className="banner_section">
    <NavMenuBar/>
    <div className="container">
        <div className="map">

        </div>
    </div>
</div>
<div className="touching_with_section">
    <h3 className="title"> Get in Touch with Our Experts. </h3>
    <p className="sub_title"> Tailoring each moment to your furry companion's individual needs.</p>
    <div className="container">

        <div className="wrapper">
            <div className="part_one">
                <input placeholder="First name"/>
                <input placeholder="Email address"/>
                <input placeholder="Mobile number"/>
            </div>
            <div className="part_two">
                <textarea placeholder="Additional Message"/>
            </div>
        </div>
        <button className="primay_button">Submit</button>
    </div>
</div>

            </main>
            <Footer/>
        </div>
        </>
    )
}