import Head from "next/head";
import React from "react";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Lumyn | FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="main frequently_asked_questions">
          <div className={"faq_section"}>
            <NavMenuBar />
            <div className={"bredcrumb"}>
              <span>Home</span>
              <span>{">"}</span>
              <span className={"active"}>Frequently asked questions</span>
            </div>
            <h3 className={"title"}> Where Your Queries Find Answers </h3>
            <p className={"sub_title"}>
              tailoring each moment to your furry companion's individual needs.
            </p>
            <div className={"container"}>
              <div className="seperator" />
              <div className="question_container">
                <div className="head">
                  <h3 className="question">
                    1. What services does Lumyn offer?
                  </h3>
                  <div className="drop_drown">
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  Lumyn offers a wide range of services including podcast room
                  setup, SEO, social media marketing (SMM), website and
                  e-commerce development, LED panel solutions, and content
                  creation. Our goal is to enhance your brand visibility,
                  engagement, and overall marketing strategy.
                </div>
              </div>
              <div className="seperator" />
              <div className="question_container">
                <div className="head">
                  <h3 className="question">
                    2. How can Lumyn help improve my brand’s visibility?
                  </h3>
                  <div className="drop_drown" >
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  We specialize in creating tailored solutions such as dynamic
                  LED panels, targeted SEO strategies, and engaging content that
                  effectively capture attention and boost your brand’s online
                  and offline presence. Our approach ensures long-term
                  visibility and consistent brand recognition.
                </div>
              </div>
              <div className="seperator" />
              <div className="question_container">
                <div className="head">
                  <h3 className="question">
                    3. What makes Lumyn’s content creation services unique?
                  </h3>
                  <div className="drop_drown">
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  At Lumyn, we focus on creating content that resonates with
                  your target audience. Our team combines creativity with
                  strategic insights to produce eye-catching visuals, compelling
                  narratives, and dynamic content that drives engagement and
                  conversions.
                </div>
              </div>
              <div className="seperator" />
              <div className="question_container">
                <div className="head">
                  <h3 className="question">
                    4. Can Lumyn help with social media marketing?
                  </h3>
                  <div className="drop_drown">
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  Yes! Our social media marketing services are designed to
                  increase your brand’s reach, engage with your audience, and
                  drive traffic. We create targeted campaigns, manage platforms,
                  and deliver results that align with your business objectives.
                </div>
              </div>
              <div className="seperator" />
              <div className="seperator" />
              <div className="question_container">
                
                <div className="head">
                  
                  <h3 className="question">
                    
                    5. How does Lumyn’s SEO services work?
                  </h3>
                  <div className="drop_drown">
                    
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  
                  Our SEO strategies are built to improve your website’s search
                  engine ranking through keyword optimization, on-page SEO, and
                  quality content. We focus on driving organic traffic,
                  increasing visibility, and ensuring your business reaches the
                  right audience at the right time.
                </div>
              </div>
              <div className="seperator" />
              <div className="question_container">
                
                <div className="head">
                  
                  <h3 className="question">
                    
                    6. Do you offer customized services for specific industries?
                  </h3>
                  <div className="drop_drown">
                    
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  
                  Yes, Lumyn offers tailored solutions for a variety of
                  industries. Whether you’re in retail, technology, education,
                  or any other sector, we customize our services to fit your
                  unique business needs and goals.
                </div>
              </div>
              <div className="seperator" />
              <div className="question_container">
                
                <div className="head">
                  
                  <h3 className="question">
                    
                    7. How can Lumyn help me stand out from my competitors?
                  </h3>
                  <div className="drop_drown">
                    
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  
                  We position your brand with a competitive edge by focusing on
                  consistency, customer loyalty, and credibility. Our
                  comprehensive approach, including corporate branding, SEO, and
                  innovative marketing solutions, ensures your brand stands out
                  and generates lasting trust with your audience
                </div>
              </div>
              <div className="seperator" />
              <div className="question_container">
                
                <div className="head">
                  
                  <h3 className="question">
                    
                    8. How do I get started with Lumyn’s services?
                  </h3>
                  <div className="drop_drown">
                    
                    <svg
                      width="14"
                      height="9"
                      viewBox="0 0 14 9"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      
                      <path
                        d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                        fill="#2DFF28"
                      />
                    </svg>
                  </div>
                </div>
                <div className="body">
                  
                  Getting started is easy! Simply reach out to us through our
                  contact page, and we’ll schedule a consultation to understand
                  your needs. From there, we’ll develop a customized plan to
                  help your brand achieve its goals.
                </div>
              </div>
              <div className="question_container">
    <div className="head">
        <h3 className="question">
            9. Will Lumyn help with brand strategy development?
        </h3>
        <div className="drop_drown">
            <svg
                width="14"
                height="9"
                viewBox="0 0 14 9"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                    fill="#2DFF28"
                />
            </svg>
        </div>
    </div>

    <div className="body">
        Absolutely! We work with you to define your brand strategy,
        ensuring it aligns with your business goals and resonates with
        your target audience. Our team helps you build strong brand
        equity and customer loyalty, positioning your brand for
        long-term success.
    </div>
</div>
<div className="seperator" />
<div className="question_container">
    <div className="head">
        <h3 className="question">
            10. How long does it take to see results from your services?
        </h3>
        <div className="drop_drown">
            <svg
                width="14"
                height="9"
                viewBox="0 0 14 9"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
            >
                <path
                    d="M13.5898 2.72364C14.1367 2.20288 14.1367 1.35762 13.5898 0.836861C13.0429 0.316099 12.1553 0.316098 11.6084 0.836861L6.99691 5.22801L2.38818 0.83686C1.84129 0.316098 0.953623 0.316098 0.40948 0.83686C0.137409 1.09593 -4.33896e-08 1.43875 -5.82628e-08 1.77894C-7.3136e-08 2.11914 0.137409 2.46195 0.40948 2.72102L6.0103 8.05426C6.5572 8.57502 7.44486 8.57502 7.98901 8.05426L13.5898 2.72364Z"
                    fill="#2DFF28"
                />
            </svg>
        </div>
    </div>

    <div className="body">
        The timeline for seeing results varies depending on the
        service. SEO and content marketing may take a few months to
        show significant results, while branding and content creation
        can have a more immediate impact. We work closely with you to
        set realistic expectations and track progress along the way.
    </div>
</div>
<div className="seperator" />

            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}
