import Head from "next/head";
import Image from "next/image";

import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

import Carousel from "react-multi-carousel";


export default function Home() {
  return (
    <>
      <Head>
        <title>Lumyn | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="main home">
          <div className="banner_section">
            <NavMenuBar />

            {/* <div className="star_container">
            <h2 className="title_one"> <span>LUMYN:</span> WHERE</h2>
          <Image className="star" src="/assets/svg/star.svg" width={150} height={150} alt="star" />
        </div>

      <h2 className="title_two">FINDS <span>LIGHT</span></h2> */}
            <button className="primay_button"   onClick={() => (window.location.href = '/products')}
            >Learn More</button>
          </div>

          <div className="section_one">
            <div className="top">
              <h3> See how Lumyn transforms brands into industry leaders </h3>
              <p>
                Ignite your success with bold strategies, creative
                solutions, and unmatched passion!
              </p>
            </div>
            {/* <div className="image_container"></div> */}
            <div className="bottom">
              <div className="container">
                <div className="item">
                  <h3>100+</h3>
                  <p>Projects Completed</p>
                </div>
                <div className="item">
                  <h3>50+</h3>
                  <p>Total Customers</p>
                </div>
                <div className="item">
                  <h3>50K+</h3>
                  <p>Dedicated Hours</p>
                </div>
                <div className="item">
                  <h3>4.8/5</h3>
                  <p>Customer Satisfaction</p>
                </div>
              </div>
              {/* <p className="mobile text_description">
                Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
                posuere cubilia curae; Vestibulum dictum congue lorem vel
                varius.
              </p> */}
<a href="https://wa.me/message/UQCKZRNUKEGRL1" target="_blank" rel="noopener noreferrer">
  <button className="primay_button">Get Connected</button>
</a>
            </div>
          </div>

          <div className="inter_mediate_section">
            <span>
              * Silent Speed, Green Adventure * Silent Speed, Green Adventure *
              Silent Speed, Green Adventure *
            </span>
          </div>

          <div className="section_two">
            <div className="top">
              <h3> What We Offer </h3>
              <p>Services Designed to Make Your Brand Unforgettable</p>
            </div>

            <Carousel
              additionalTransfrom={0}
              arrows
              autoPlaySpeed={3000}
              centerMode={false}
              className=""
              containerClass=""
              dotListClass=""
              draggable
              focusOnSelect={false}
              infinite={true}
              itemClass=""
              keyBoardControl
              minimumTouchDrag={80}
              pauseOnHover
              renderArrowsWhenDisabled={false}
              renderButtonGroupOutside={false}
              renderDotsOutside={true}
              // responsive={{
              //   desktop: {
              //     breakpoint: {
              //       max: 3000,
              //       min: 1024,
              //     },
              //     items: 3,
              //     partialVisibilityGutter: 30,
              //   },
              //   mobile: {
              //     breakpoint: {
              //       max: 768,
              //       min: 0,
              //     },
              //     items: 1,
              //     partialVisibilityGutter: 25,
              //   },
              //   tablet: {
              //     breakpoint: {
              //       max: 1024,
              //       min: 768,
              //     },
              //     items: 2,
              //     partialVisibilityGutter: 20,
              //   },
              // }}
              responsive={{
                desktop: {
                  breakpoint: {
                    max: 3000,
                    min: 1025, // Starts from 1025 to avoid overlap with tablet
                  },
                  items: 3,
                  partialVisibilityGutter: 30,
                },
                mobile: {
                  breakpoint: {
                    max: 767, // Ends at 767 to avoid overlap with tablet
                    min: 0,
                  },
                  items: 1,
                  partialVisibilityGutter: 25,
                },
                tablet: {
                  breakpoint: {
                    max: 1024, // Ends at 1024 to avoid overlap with desktop
                    min: 768, // Starts from 768 to avoid overlap with mobile
                  },
                  items: 2,
                  partialVisibilityGutter: 20,
                },
              }}
              
              rewind={false}
              rewindWithAnimation={false}
              rtl={false}
              shouldResetAutoplay
              showDots={true}
              sliderClass=""
              slidesToSlide={1}
              swipeable
            >
              <div className="item" style={{ width: "100%" }}>
                <div className="img img_1">
                  {/* <div className="star_container">
                    <div className="star"></div>
                  </div> */}
                </div>

                <div className="bottom">
                  <h4 className="title">BrandForge</h4>
                  <p className="sub_title">
                    Create a memorable brand that resonates.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-01.svg"
                        width={36}
                        height={35}
                        alt="map-point"
                      />
                      Brand Development
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-02.svg"
                        width={36}
                        height={35}
                        alt="map-point"
                      />
                      Identity Design
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-03.svg"
                        width={36}
                        height={35}
                        alt="map-point"
                      />
                      Strategic Positioning
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_2"></div>
                <div className="bottom">
                  <h4 className="title">WebCommerce</h4>
                  <p className="sub_title">
                    Professional visuals that beautifully narrate your brand’s
                    story.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-04.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      E-Commerce Solutions
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-05.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Custom Web Design
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-06.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Conversion Optimization
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_3"></div>
                <div className="bottom">
                  <h4 className="title">ProjeXpert</h4>
                  <p className="sub_title">
                    Streamline projects with optimized workflows and expert
                    management.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-10.svg"
                        width={36}
                        height={35}
                        alt="map-point"
                      />
                      Project Management
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-11.svg"
                        width={36}
                        height={35}
                        alt="map-point"
                      />
                      Workflow Optimization
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-12.svg"
                        width={36}
                        height={35}
                        alt="map-point"
                      />
                      Efficient Execution
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_4">
                  
                </div>
                <div className="bottom">
                  <h4 className="title">CutCraft Studios</h4>
                  <p className="sub_title">
                    Turn ideas into engaging, impactful videos with expert
                    editing.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-13.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Content Editing
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-14.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Video editing
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-15.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Refined Storytelling
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_5"></div>
                <div className="bottom">
                  <h4 className="title">MarketBlaze</h4>
                  <p className="sub_title">
                    Fuel business growth with targeted marketing and data-driven
                    campaigns.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-16.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Marketing Strategies
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-17.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      SEO Campaigns
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-18.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Ad Optimization
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_6"></div>
                <div className="bottom">
                  <h4 className="title">Customease</h4>
                  <p className="sub_title">
                    Experience personalized solutions with client-first
                    innovation and support.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-19.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Custom Solutions
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-20.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Tailored Services
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-21.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Client-Centric Support
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_7"></div>
                <div className="bottom">
                  <h4 className="title">SocialMuse</h4>
                  <p className="sub_title">
                    Grow and nurture your audience with expertly managed social
                    platforms.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-22.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Social Media Marketing
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-23.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Content Curation
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-24.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Audience Engagement
                    </div>
                  </div>
                </div>
              </div>

              <div className="item" style={{ width: "100%" }}>
                <div className="img img_8"></div>
                <div className="bottom">
                  <h4 className="title">InsightMedia</h4>
                  <p className="sub_title">
                    Navigate the ever-evolving media landscape with confidence
                    and clarity.
                  </p>
                  <div className="icon_highlight">
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-25.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Data Analytics
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-26.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Performance Tracking
                    </div>
                    <div className="wrapper">
                      <Image
                        src="/assets/svg/WWO Icons-18.svg"
                        width={35}
                        height={35}
                        alt="map-point"
                      />
                      Growth Insights
                    </div>
                  </div>
                </div>
              </div>
            </Carousel>

            {/* 
  <div className="card_container_mobile">
       <Carousel 
                    additionalTransfrom={0}
                    arrows
                    autoPlaySpeed={3000}
                    centerMode={false}
                    className=""
                    containerClass=""
                    dotListClass="slide_dot"
                    draggable
                    focusOnSelect={false}
                    infinite={true}
                    itemClass=""
                    keyBoardControl
                    minimumTouchDrag={80}
                    pauseOnHover
                    renderArrowsWhenDisabled={false}
                    renderButtonGroupOutside={true}
                    renderDotsOutside={true}
                    responsive={{
                      desktop: {
                        breakpoint: {
                          max: 3000,
                          min: 1024
                        },
                        items: 1,
                        partialVisibilityGutter: 30
                      },
                      mobile: {
                        breakpoint: {
                          max: 464,
                          min: 0
                        },
                        items: 1,
                        partialVisibilityGutter: 25
                      },
                      tablet: {
                        breakpoint: {
                          max: 1024,
                          min: 464
                        },
                        items: 1,
                        partialVisibilityGutter: 20
                      }
                    }}
                    rewind={false}
                    rewindWithAnimation={false}
                    rtl={false}
                    shouldResetAutoplay
                    showDots={true}
                    sliderClass=""
                    slidesToSlide={1}
                    swipeable
                  >
                    <div className="item" style={{width:"100%",height:'500px',backgroundColor:'red'}}></div>
                    <div className="item" style={{width:"100%",height:'500px',backgroundColor:'yellow'}}></div>
                    <div className="item" style={{width:"100%",height:'500px',backgroundColor:'orange'}}></div>


                  </Carousel>

  </div> */}
          </div>

          <div className="section_three_mobile mobile">
            <h3 className="title">Exclusive Highlight</h3>
            <p className="sub_title">Experience innovation at its finest.</p>

            <Carousel
              additionalTransfrom={0}
              arrows
              autoPlaySpeed={3000}
              centerMode={false}
              className=""
              containerClass=""
              dotListClass="slide_dot"
              draggable
              focusOnSelect={false}
              infinite={true}
              itemClass=""
              keyBoardControl
              minimumTouchDrag={80}
              pauseOnHover
              renderArrowsWhenDisabled={false}
              renderButtonGroupOutside={true}
              renderDotsOutside={true}
              responsive={{
                desktop: {
                  breakpoint: {
                    max: 3000,
                    min: 1024,
                  },
                  items: 1,
                  partialVisibilityGutter: 30,
                },
                mobile: {
                  breakpoint: {
                    max: 464,
                    min: 0,
                  },
                  items: 1,
                  partialVisibilityGutter: 25,
                },
                tablet: {
                  breakpoint: {
                    max: 1024,
                    min: 464,
                  },
                  items: 1,
                  partialVisibilityGutter: 20,
                },
              }}
              rewind={false}
              rewindWithAnimation={false}
              rtl={false}
              shouldResetAutoplay
              showDots={true}
              sliderClass=""
              slidesToSlide={1}
              swipeable
            >


              <div className="image_container image_container_1" >
                <div className="text_container">
                  <div className="bar">
                    <div className="inner_bar"></div>
                  </div>
                  <div className="wrapper">
                    <h3 className="title">EchoPod</h3>
                  <p className="description">
                    “Professional Space for Creative Voices”
                    <br />A state-of-the-art facility designed to produce
                    polished and impactful podcasts.
                  </p>
                  <p className="number">01</p>
                  </div>
                </div>
              </div>


              <div className="image_container image_container_2">
                <div className="text_container">
                  <div className="bar">
                    <div className="inner_bar"></div>
                  </div>
                  <div className="wrapper">
                  <h3 className="title">OptiRank</h3>
                  <p className="description">
                    “Rank Higher, Shine Brighter.”
                    <br />
                    Boost your search engine visibility with proven strategies
                    that drive organic traffic.
                  </p>
                  <p className="number">02</p>
                  </div>
                </div>
              </div>

              <div className="image_container image_container_3">
                <div className="text_container">
                  <div className="bar">
                    <div className="inner_bar"></div>
                  </div>
                  <div className="wrapper">
                  <h3 className="title">LumaPanels</h3>
                  <p className="description">
                  "Vivid Displays That Captivate"
                    <br />
                    Showcase your brand with vibrant, attention-grabbing LED panels.                  </p>
                  <p className="number">03</p>
                  </div>
                </div>
              </div>

              <div className="image_container image_container_4">
                <div className="text_container">
                  <div className="bar">
                    <div className="inner_bar"></div>
                  </div>
                  <div className="wrapper">
                  <h3 className="title">ContentAura</h3>
                  <p className="description">
                    “E“Compelling Stories That Convert”
                    <br />
                    Bring your brand to life with tailored content that connects and converts.
                  </p>
                  <p className="number">04</p>
                  </div>
                </div>
              </div>


            </Carousel>


          </div>

          <div className="section_three">
            <div className="high_light">
              <h3 className="title">Exclusive Highlights</h3>
              <div className="bar"></div>
              <p className="description">
              From top-tier podcast rooms and expert SEO strategies to dynamic 
              LED panels and captivating content creation—boost visibility, 
              engage your audience, and drive unstoppable results.
              </p>
            </div>

            <div className="card">
              <div className="image_container padding">
                <div className="image podcast_room" />
              </div>

              <div className="bottom">
                <div className="strip">
                  <div className="con"></div>
                </div>
                <div className="wrapper">
                  <h3 className="title">EchoPod</h3>
                  <p className="description">
                    “Professional Space for Creative Voices”
                    <br />A state-of-the-art facility designed to produce
                    polished and impactful podcasts.
                  </p>
                  <p className="number">01</p>
                </div>
              </div>
            </div>

            <div className="card">
              <div className="image_container padding">
                <div className="image seo_service" />
              </div>

              <div className="bottom">
                <div className="strip">
                  <div className="con"></div>
                </div>
                <div className="wrapper">
                  <h3 className="title">OptiRank</h3>
                  <p className="description">
                    “Rank Higher, Shine Brighter.”
                    <br />
                    Boost your search engine visibility with proven strategies
                    that drive organic traffic.
                  </p>
                  <p className="number">02</p>
                </div>
              </div>
            </div>

            <div className="card">
              <div className="image_container padding">
                <div className="image led_panel" />
              </div>

              <div className="bottom">
                <div className="strip">
                  <div className="con"></div>
                </div>
                <div className="wrapper">
                  <h3 className="title">LumaPanels</h3>
                  <p className="description">
                  "Vivid Displays That Captivate"
                  <br />
                    Showcase your brand with vibrant, attention-grabbing LED panels.                  </p>
                  <p className="number">03</p>
                </div>
              </div>
            </div>

            <div className="card">
              <div className="image_container">
                <div className="image content_creation" />
              </div>

              <div className="bottom">
                <div className="strip">
                  <div className="con"></div>
                </div>
                <div className="wrapper">
                  <h3 className="title">ContentAura</h3>
                  <p className="description">
                    “E“Compelling Stories That Convert”
                    <br />
                    Bring your brand to life with tailored content that connects and converts.
                  </p>
                  <p className="number">04</p>
                </div>
              </div>
            </div>
          </div>

          <div className="section_four">
            <div className="middle">
              <h3 className="title">About Lumyn</h3>
              <p className="description">
                We believe that every brand has its own light, waiting to shine.
                Our mission is to help you find that glow, amplify it, and let
                it illuminate the world. Just as fireflies illuminate their
                surroundings with effortless grace, Lumyn ignites the spark
                within brands, helping them shine brighter, reach farther, and
                captivate audiences with their unique stories. Every strategy,
                campaign, and design we create is like a firefly’s
                light—distinctive, purposeful, and unforgettable.
              </p>
              <a href="https://wa.me/message/UQCKZRNUKEGRL1" target="_blank" rel="noopener noreferrer">
  <button className="primay_button">Get Connected</button>
</a>
            </div>

            <div className="bottom">
              <div className="container">
                <div className="left"></div>
                <div className="right">
                  <h3 className="title">Code Crafted by Lumyn</h3>
                  <p className="sub_title">
                  Your digital presence, redefined with bespoke web solutions.

                  </p>

                  <div className="container">
                  <div className="item">Responsive Development</div>

                    <div className="item">Custom Designs</div>
                    <div className="item">SEO Optimization</div>
                    <div className="item">Fast Loading Speed </div>
                    <div className="item">Security First </div>
                    <div className="item">Scalable Solutions</div>
                    <div className="item">Expert Support </div>

                  </div>
                  {/* <p className="mobile text_description">
                  Your website is your brand’s digital home—it should be as distinct as your business. At Code Crafted, we build custom websites that reflect your unique identity and align seamlessly with your goals.
                  </p> */}
                    <h4>Why Choose Lumyn for Your Website?</h4> 

                    <p className="text">At Lumyn, we understand that your website isn’t just a platform—it’s a cornerstone of your brand identity. 
                      It’s the first impression many customers will have of your business, and it needs to combine aesthetics, performance, and 
                      functionality to stand out in today’s competitive digital landscape.
                    </p>
                    <h4>Let’s Build Something Extraordinary!!</h4> 
<p className="text">Your website should be as dynamic and forward-thinking as your business. 
  At Lumyn, we merge creativity with technology to deliver websites that are more than just functional—they’re 
  transformative.
</p>
<button
  className="primay_button"
  onClick={() => (window.location.href = '/contact-us')}
>
  Contact Us
</button>
                </div>
              </div>
            </div>
          </div>

          <div className="section_five">
            <div className="top">
              <h3>
                {" "}
                What's New?
                <br />
                Check Out Our Blog
              </h3>
              <p>
                From fresh ideas to trending topics, our blog covers it all.
              </p>
            </div>

            <div className="card_container">
              <div className="card blog_image_1">
                <div className="bottom">
                  <p className="sub_title">By Admin   </p>
                  <h4 className="title"> 
                  Driving Organic Traffic: Essential Strategies for 2025

                  </h4>
                </div>
              </div>
              <div className="card blog_image_2">
                <div className="bottom">
                  <p className="sub_title">By Admin   </p>
                  <h4 className="title">
                  Domain Privacy Protection: Why It's Essential for Website Owners
                  </h4>
                </div>
              </div>
              <div className="card blog_image_3">
                <div className="bottom">
                  <p className="sub_title">By Admin   </p>
                  <h4 className="title">
                  Website Revamping: A Strategic Approach to Business Growth

                  </h4>
                </div>
              </div>
            </div>

            <Carousel
              additionalTransfrom={0}
              arrows
              autoPlaySpeed={3000}
              centerMode={false}
              className=""
              containerClass=""
              dotListClass="slide_dot"
              draggable
              focusOnSelect={false}
              infinite={true}
              itemClass=""
              keyBoardControl
              minimumTouchDrag={80}
              pauseOnHover
              renderArrowsWhenDisabled={false}
              renderButtonGroupOutside={true}
              renderDotsOutside={true}
              responsive={{
                desktop: {
                  breakpoint: {
                    max: 3000,
                    min: 1024,
                  },
                  items: 1,
                  partialVisibilityGutter: 30,
                },
                mobile: {
                  breakpoint: {
                    max: 464,
                    min: 0,
                  },
                  items: 1,
                  partialVisibilityGutter: 25,
                },
                tablet: {
                  breakpoint: {
                    max: 1024,
                    min: 464,
                  },
                  items: 1,
                  partialVisibilityGutter: 20,
                },
              }}
              rewind={false}
              rewindWithAnimation={false}
              rtl={false}
              shouldResetAutoplay
              showDots={true}
              sliderClass=""
              slidesToSlide={1}
              swipeable
            >
              <div className="card">
                <div className="bottom">
                  <p className="sub_title">By Admin   </p>
                  <h4 className="title">
                  Driving Organic Traffic: Essential Strategies for 2024

                  </h4>
                  <a className="view_more"> View more </a>
                </div>
              </div>

              <div className="card">
                <div className="bottom">
                  <p className="sub_title">By Admin   </p>
                  <h4 className="title">
                  Domain Privacy Protection: Why It's Essential for Website Owners

                  </h4>
                  <a className="view_more"> View more </a>
                </div>
              </div>

              <div className="card">
                <div className="bottom">
                  <p className="sub_title">By Admin   </p>
                  <h4 className="title">
                  Website Revamping: A Strategic Approach to Business Growth

                  </h4>
                  <a className="view_more"> View more </a>
                </div>
              </div>
            </Carousel>
          </div>

          <div className="section_six">
            <h3 className="title">
              We've made our presence <br /> known across the globe{" "}
            </h3>

            <div className="container">

              <div className="item">
                 <img src="/assets/images/UAE.png" alt="" />
                 <h4>UAE</h4>
              </div>
              <div className="item">
                 <img src="/assets/images/india.png" alt="" />
                 <h4>INDIA</h4>
              </div>
              <div className="item">
                 <img src="/assets/images/UK.png" alt="" />
                 <h4>UK</h4>
              </div>
              <div className="item">
                 <img src="/assets/images/USA.png" alt="" />
                 <h4>USA</h4>
              </div>

            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}

{

}
