import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";
import Rating from "@/component/rating";

import Carousel from "react-multi-carousel";

export default function Podcast() {
  return (
    <>
      <Head>
        <title>Lumyn | Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="main podcast">
          <div className="banner_section">
            <NavMenuBar />

            <div className="container">
              <h3 className="title">YOUR VOICE , <span>YOUR STORY</span> <br/> <span>WITH LUMYN </span>PODCAST ROOMS</h3>
              <p className="sub_title">Step into our state-of-the-art studios and produce podcasts that captivate. Crystal-clear sound, flawless recordings – tell your story with impact.</p>
              <button className="primay_button">Book Today</button>
            </div>
          </div>

          <div className="section_one">
            <div className="wrapper">

              <div className="amplify_your_voice">
                <h3 className="title">Ready to <span>Amplify</span> Your Voice?</h3>
              </div>

              <div className="container">
                <h3 className="title">Your Story Deserves the Best</h3>
                <p className="sub_title">
                  Book & start creating content that makes an impact
                </p>

                <div className="amplify_your_voice_mobile mobile">
                <h3 className="title">Ready to <span>Amplify</span> Your Voice?</h3>
                </div>

                <div className="card_container">
                  <div className="card">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">Echo Lite 
                      </h4>
                    </div>
                  </div>
                  <div className="card">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">Resonance Pro 
                      </h4>
                    </div>
                  </div>
                  <div className="card">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">Sonic Max</h4>
                    </div>
                  </div>
                </div>

                <Carousel 
                  additionalTransfrom={0}
                  arrows
                  autoPlaySpeed={3000}
                  centerMode={false}
                  className=""
                  containerClass=""
                  dotListClass="slide_dot"
                  draggable
                  focusOnSelect={false}
                  infinite={true}
                  itemClass=""
                  keyBoardControl
                  minimumTouchDrag={80}
                  pauseOnHover
                  renderArrowsWhenDisabled={false}
                  renderButtonGroupOutside={true}
                  renderDotsOutside={true}
                  responsive={{
                    desktop: {
                      breakpoint: {
                        max: 3000,
                        min: 1024
                      },
                      items: 1,
                      partialVisibilityGutter: 30
                    },
                    mobile: {
                      breakpoint: {
                        max: 464,
                        min: 0
                      },
                      items: 1,
                      partialVisibilityGutter: 25
                    },
                    tablet: {
                      breakpoint: {
                        max: 1024,
                        min: 464
                      },
                      items: 1,
                      partialVisibilityGutter: 20
                    }
                  }}
                  rewind={false}
                  rewindWithAnimation={false}
                  rtl={false}
                  shouldResetAutoplay
                  showDots={true}
                  sliderClass=""
                  slidesToSlide={1}
                  swipeable
                >
                  <div className="item">
                    <div className="bottom">
                      <span>Echo Lite 
                      </span>
                    </div>

                  </div>
                  <div className="item" >
                  <div className="bottom">
                      <span>Resonance Pro 
                      </span>
                    </div>
                  </div>
                  <div className="item" >
                  <div className="bottom">
                      <span>Sonic Max</span>
                    </div>
                  </div>


                </Carousel>


              </div>

            </div>

            <div className="offer_container">
              <span> Grab this limited time deal :</span>
            </div>
          </div>

          <div className="section_section">

            <div className="span">
<div className="one"></div>
<div  className="two">
<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="11" cy="11" r="11" fill="url(#paint0_linear_692_162)"/>
<defs>
<linearGradient id="paint0_linear_692_162" x1="9.06667" y1="-8" x2="-6.8791" y2="2.00519" gradientUnits="userSpaceOnUse">
<stop stop-color="#17935C"/>
<stop offset="1" stop-color="#184B35"/>
</linearGradient>
</defs>
</svg>
</div>
<div className="three"></div>
            </div>
            <div className="container">


          <div className="section_two">
            <div className="part_one">
              <div className="wrapper">
                <h3 className="title">
                  Create. Inspire. Amplify: Podcasting Reimagined
                </h3>
                <p className="sub_title">
                  Podcasts are more than just audio; the space where your voice
                  takes center stage. Professionally crafted podcast rooms
                  designed to elevate your story.
                </p>
                <div className="container">
                  <div className="item"></div>
                </div>
              </div>
            </div>
            <div className="part_two"></div>
          </div>

          <div className="section_three">
            <div className="part_one"></div>
            <div className="part_two">
              <div className="wrapper">
                <h3 className="title">
                Where Innovation Meets Creativity
                </h3>
                <p className="sub_title">
                Our podcast rooms are designed for creators, by creators. 
                Experience a seamless blend of advanced technology and creative freedom to produce content that stands out. 
                Whether you’re a seasoned podcaster or just starting out, we’ve got everything you need to succeed.
                </p>
                <div className="container">
                  <div className="item">
                    <div className="title">Professional Soundproofing</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="title">Professional Soundproofing</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="title">Professional Soundproofing</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="section_four">
            <div className="part_one">
              <div className="wrapper">
                <h3 className="title">
                A Space to Create Without Limits
                </h3>
                <p className="sub_title">
                From podcast enthusiasts to business professionals, we cater to all your needs with a range of flexible services.
                </p>
                <div className="container">
                  <div className="item"></div>
                  <div className="item"></div>
                  <div className="item"></div>
                  <div className="item"></div>
                </div>
                <button className="primay_button">Book Today</button>
              </div>
            </div>

            <div className="part_two"></div>
          </div>


            </div>

          </div>



          <div className="section_five">
            <div className="image"></div>
            <div className="title">Book Your Podcasting Experience</div>
            <div className="rate_container"></div>
            <div className="wrapper">
              <span> Choose Your Package </span>
              <span> Pick a Time Slot </span>
              <span> Confirm Your Booking </span>
            </div>
            <button className="primay_button">Book Now</button>
          </div>

          <div className="section_six">
            <h4 className="title">Transforming Ideas into Impactful Podcasts</h4>

            <div className="container">
              <div className="item">
                <Rating number={4} />
                <p className="testimonial">
                "The team at Lumyn made the entire process effortless.
                 From the moment I stepped into the studio, everything was perfectly set up.
                  My podcast has never sounded so professional!"
                </p>
                <p className="author">
                  Ernest Alford{" "}
                  <span className="designation">, Ui designer </span>
                </p>
              </div>
            </div>

            <div className="qoute">
              <svg
                width="184"
                height="151"
                viewBox="0 0 184 151"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  opacity="0.09"
                  d="M166.011 78.1583C178.004 78.1583 184 84.5704 184 97.3946V131.764C184 144.588 178.004 151 166.011 151H125.922C113.929 151 107.933 144.588 107.933 131.764V97.3946C107.933 75.3369 109.389 56.87 112.302 41.9939C115.214 26.9468 122.667 14.8065 134.659 5.57305C143.397 -1.09556 150.25 -1.77952 155.218 3.52117L164.983 14.0371C171.151 20.5347 170.209 26.9468 162.156 33.2734C156.674 37.5482 152.991 43.1053 151.106 49.9449C149.222 56.7845 148.279 66.189 148.279 78.1583H166.011ZM58.0782 78.1583C70.0708 78.1583 76.067 84.5704 76.067 97.3946V131.764C76.067 144.588 70.0708 151 58.0782 151H17.9888C5.99628 151 0 144.588 0 131.764V97.3946C0 75.3369 1.45624 56.87 4.36872 41.9939C7.28119 26.9468 14.7337 14.8065 26.7263 5.57305C35.4637 -1.09556 42.3166 -1.77952 47.2849 3.52117L57.0503 14.0371C63.2179 20.5347 62.2756 26.9468 54.2235 33.2734C48.7412 37.5482 45.0577 43.1053 43.1732 49.9449C41.2886 56.7845 40.3464 66.189 40.3464 78.1583H58.0782Z"
                  fill="white"
                />
              </svg>
            </div>
          </div>

          <div className="section_seven">
            <div className="container">
              <div className="part_one">
                {/* <div className="column">
                  <div className="item"></div>
                  <div className="item"></div>
                  <div className="item"></div>
                </div>
                <div className="column"></div>
                <div className="column"></div> */}
              </div>

              <div className="part_two">
                <h3 className="title">Follow Us @Teamlumyn</h3>
                <div className="team mobile">
                <svg width="32" height="33" viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clipPath="url(#clip0_4168_216)">
<path d="M15.8964 32.9288H7.82349C7.82349 28.4441 4.25662 24.7927 -0.131226 24.7927V16.5356C8.70666 16.5356 15.8964 23.8894 15.8964 32.9288Z" fill="#00EC84"/>
<path d="M23.8542 32.9288H15.7813C15.7813 23.8894 22.971 16.5356 31.8089 16.5356V24.7927C27.4242 24.7927 23.8542 28.4409 23.8542 32.9288Z" fill="#00EC84"/>
<path d="M31.8089 16.6691C22.971 16.6691 15.7813 9.31534 15.7813 0.275879H23.8542C23.8542 4.76062 27.4211 8.41203 31.8089 8.41203V16.6691Z" fill="#00EC84"/>
<path d="M-0.131226 16.6691V8.41203C4.25351 8.41203 7.82349 4.7638 7.82349 0.275879H15.8964C15.8964 9.31534 8.70666 16.6691 -0.131226 16.6691Z" fill="#00EC84"/>
</g>
<defs>
<clipPath id="clip0_4168_216">
<rect width="32" height="33" fill="white"/>
</clipPath>
</defs>
</svg>
<p className="lumyn_text">@Team Lumyn</p>
                </div>
              </div>
            </div>
          </div>

        </main>

        <Footer />
      </div>
    </>
  );
}
