import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";
import Rating from "@/component/rating";

export default function Podcast() {
  return (
    <>
      <Head>
        <title>Lumyn | Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="main podcast">
          <div className="banner_section">
            <NavMenuBar />

            <div className="container">
              <h3 className="title"></h3>
              <p className="title"></p>
              <button></button>
            </div>
          </div>

          <div className="section_one">
            <div className="wrapper">
              <div className="amplify_your_voice">
                <h3 className="title">Ready to Amplify Your Voice?</h3>
              </div>

              <div className="container">
                <h3 className="title">Your Story Deserves the Best</h3>
                <p className="sub_title">
                  Book & start creating content that makes an impact
                </p>

                <div className="card_container">
                  <div className="card">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">NovaVision Glasses Pro 2</h4>
                    </div>
                  </div>
                  <div className="card">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">NovaVision Glasses Pro 2</h4>
                    </div>
                  </div>
                  <div className="card">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">NovaVision Glasses Pro 2</h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="offer_container">
              <span> Grab this limited time deal :</span>
            </div>
          </div>

          <div className="section_two">
            <div className="part_one">
              <div className="wrapper">
                <h3 className="title">
                  Create. Inspire. Amplify: Podcasting Reimagined
                </h3>
                <p className="sub_title">
                  Podcasts are more than just audio; the space where your voice
                  takes center stage. Professionally crafted podcast rooms
                  designed to elevate your story.
                </p>
                <div className="container">
                  <div className="item"></div>
                </div>
              </div>
            </div>
            <div className="part_two"></div>
          </div>

          <div className="section_three">
            <div className="part_one"></div>
            <div className="part_two">
              <div className="wrapper">
                <h3 className="title">
                  Create. Inspire. Amplify: Podcasting Reimagined
                </h3>
                <p className="sub_title">
                  Podcasts are more than just audio; the space where your voice
                  takes center stage. Professionally crafted podcast rooms
                  designed to elevate your story.
                </p>
                <div className="container">
                  <div className="item">
                    <div className="title">Professional Soundproofing</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="title">Professional Soundproofing</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="title">Professional Soundproofing</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="section_four">
            <div className="part_one">
              <div className="wrapper">
                <h3 className="title">
                  Create. Inspire. Amplify: Podcasting Reimagined
                </h3>
                <p className="sub_title">
                  Podcasts are more than just audio; the space where your voice
                  takes center stage. Professionally crafted podcast rooms
                  designed to elevate your story.
                </p>
                <div className="container">
                  <div className="item"></div>
                </div>
                <button className="secondary_button">Book Today</button>
              </div>
            </div>

            <div className="part_two"></div>
          </div>

          <div className="section_five">
            <div className="image"></div>
            <div className="title">Book Your Podcasting Experience</div>
            <div className="rate_container"></div>
            <div className="wrapper">
              <span> Choose Your Package </span>
              <span> Pick a Time Slot </span>
              <span> Confirm Your Booking </span>
            </div>
            <button className="primay_button">Book Now</button>
          </div>

          <div className="section_six">
            <h4 className="title">What they say about us</h4>

            <div className="container">
              <div className="item">
                <Rating number={4} />
                <p className="testimonial">
                  Nunc bibendum, lacus a ornare condimentum, diam augue semper
                  nulla, in porta orci diam eget tortor. Vestibulum imperdiet
                  finibus mattis. Morbi interdum purus ut ex tristique, eget
                  pharetra lorem feugiat. Nullam ac dui eu lorem vulputate
                  luctus.
                </p>
                <p className="author">
                  Ernest Alford{" "}
                  <span className="designation">, Ui designer </span>
                </p>
              </div>
            </div>

            <div className="qoute">
              <svg
                width="184"
                height="151"
                viewBox="0 0 184 151"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  opacity="0.09"
                  d="M166.011 78.1583C178.004 78.1583 184 84.5704 184 97.3946V131.764C184 144.588 178.004 151 166.011 151H125.922C113.929 151 107.933 144.588 107.933 131.764V97.3946C107.933 75.3369 109.389 56.87 112.302 41.9939C115.214 26.9468 122.667 14.8065 134.659 5.57305C143.397 -1.09556 150.25 -1.77952 155.218 3.52117L164.983 14.0371C171.151 20.5347 170.209 26.9468 162.156 33.2734C156.674 37.5482 152.991 43.1053 151.106 49.9449C149.222 56.7845 148.279 66.189 148.279 78.1583H166.011ZM58.0782 78.1583C70.0708 78.1583 76.067 84.5704 76.067 97.3946V131.764C76.067 144.588 70.0708 151 58.0782 151H17.9888C5.99628 151 0 144.588 0 131.764V97.3946C0 75.3369 1.45624 56.87 4.36872 41.9939C7.28119 26.9468 14.7337 14.8065 26.7263 5.57305C35.4637 -1.09556 42.3166 -1.77952 47.2849 3.52117L57.0503 14.0371C63.2179 20.5347 62.2756 26.9468 54.2235 33.2734C48.7412 37.5482 45.0577 43.1053 43.1732 49.9449C41.2886 56.7845 40.3464 66.189 40.3464 78.1583H58.0782Z"
                  fill="white"
                />
              </svg>
            </div>
          </div>

          <div className="section_seven">
            <div className="container">
              <div className="part_one">
                <div className="column"></div>
                <div className="column"></div>
                <div className="column"></div>
              </div>

              <div className="part_two">
                <h3 className="title">Follow Us @Teamlumyn</h3>
              </div>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
}
