import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";
import Rating from "@/component/rating";

import Carousel from "react-multi-carousel";

export default function Podcast() {
  return (
    <>
      <Head>
        <title>Lumyn | Podcast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="main podcast">
          <div className="banner_section">
            <NavMenuBar />

            <div className="container">
  <h3 className="title">
    YOUR VOICE, <span>YOUR STORY</span> <br />
    <span>WITH LUMYN </span>PODCAST ROOMS
  </h3>
  <p className="sub_title">
    Step into our state-of-the-art studios and produce podcasts that captivate. 
    Crystal clear sound, flawless recordings – tell your story with impact.
  </p>
  <button 
    className="primay_button"
    onClick={() => window.location.href = 'https://lumyn.setmore.com/'}
  >
    Book Today
  </button>
</div>
          </div>

          <div className="section_one">
            <div className="wrapper">

              <div className="amplify_your_voice">
                <h3 className="title">Ready to <span>Amplify</span> Your Voice?</h3>
              </div>

              <div className="container">
                <h3 className="title">Your Story Deserves the Best</h3>
                <p className="sub_title">
                  Book & start creating content that makes an impact
                </p>

                <div className="amplify_your_voice_mobile mobile">
                <h3 className="title">Ready to <span>Amplify</span> Your Voice?</h3>
                </div>

                <div className="card_container">
                  <div className="card_echolite">
                    <div className="image_container">
                    {/* <img alt="shop icon" loading="lazy" width="100%" height="300" decoding="async" data-nimg="1" src="/assets/images/Echo Lite.webp"></img> */}
                    </div>
                    <div className="bottom_container">
                      <h4 className="title">Perfect sound </h4>
                      <h4 className="title">Every times </h4>
                    </div>
                  </div>
                  <div className="card_resonance_pro">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">Speak up </h4>
                      <h4 className="title">Your voice matters </h4>
                    </div>
                  </div>
                  <div className="card_sonic_max">
                    <div className="image_container"></div>
                    <div className="bottom_container">
                      <h4 className="title">Your space </h4>
                      <h4 className="title">Time to shine </h4>
                    </div>
                  </div>
                </div>

                <Carousel 
                  additionalTransfrom={0}
                  arrows
                  autoPlaySpeed={3000}
                  centerMode={false}
                  className=""
                  containerClass=""
                  dotListClass="slide_dot"
                  draggable
                  focusOnSelect={false}
                  infinite={true}
                  itemClass=""
                  keyBoardControl
                  minimumTouchDrag={80}
                  pauseOnHover
                  renderArrowsWhenDisabled={false}
                  renderButtonGroupOutside={true}
                  renderDotsOutside={true}
                  responsive={{
                    desktop: {
                      breakpoint: {
                        max: 3000,
                        min: 1024
                      },
                      items: 1,
                      partialVisibilityGutter: 30
                    },
                    mobile: {
                      breakpoint: {
                        max: 464,
                        min: 0
                      },
                      items: 1,
                      partialVisibilityGutter: 25
                    },
                    tablet: {
                      breakpoint: {
                        max: 1024,
                        min: 464
                      },
                      items: 1,
                      partialVisibilityGutter: 20
                    }
                  }}
                  rewind={false}
                  rewindWithAnimation={false}
                  rtl={false}
                  shouldResetAutoplay
                  showDots={true}
                  sliderClass=""
                  slidesToSlide={1}
                  swipeable
                >
                  <div className="item_1">
                    <div className="bottom">
                      <span>Perfect sound 
                        <br /> Every time 
                      </span>

                    </div>

                  </div>
                  <div className="item_2" >
                  <div className="bottom">
                      <span>Speak up
                        <br />Your voice matters
                      </span>
                    </div>
                  </div>
                  <div className="item_3" >
                  <div className="bottom">
                      <span>Your space
                        <br /> Time to shine</span>
                    </div>
                  </div>


                </Carousel>


              </div>

            </div>

            <div className="offer_container">
              <span> Grab this limited time deal : Book 5, Get 1 on Us!</span>
            </div>
          </div>

          <div className="section_section">

            <div className="span">
<div className="one"></div>
<div  className="two">
<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="11" cy="11" r="11" fill="url(#paint0_linear_692_162)"/>
<defs>
<linearGradient id="paint0_linear_692_162" x1="9.06667" y1="-8" x2="-6.8791" y2="2.00519" gradientUnits="userSpaceOnUse">
<stop stop-color="#17935C"/>
<stop offset="1" stop-color="#184B35"/>
</linearGradient>
</defs>
</svg>
</div>
<div className="three"></div>
            </div>
            <div className="container">


          <div className="section_two">
            <div className="part_one">
              <div className="wrapper">
                <h3 className="title">
                  Create. Inspire. Amplify: Podcasting Reimagined
                </h3>

                <p className="sub_title">
                Podcasts are more than just audio; the space where your voice takes center stage.
                Professionally crafted podcast rooms designed to elevate your story.</p>
                <p className="sub_title">  We believe every story deserves to be heard. Lumyn Echo Pod is designed to provide creators with a 
                professional, seamless, and inspiring environment to share their message. Whether you're a seasoned 
                podcaster or just starting out, we’re here to elevate your content to new heights.
                </p>
                <div className="container">
                  <div className="item"></div>
                </div>
              </div>
            </div>
            <div className="part_two">

              
            </div>
          </div>

          <div className="section_three">
            <div className="part_one"></div>
            <div className="part_two">
              <div className="wrapper">
                <h3 className="title">
                Where Innovation Meets Creativity
                </h3>
                <p className="sub_title">
                Our podcast rooms are crafted for creators, by creators. With cutting-edge technology and a focus on
                 creative freedom, these spaces enable you to produce exceptional content effortlessly. Whether you're
                  a seasoned podcaster or just starting out, we provide everything you need to succeed.
                </p>
                <div className="container">
                  <div className="item">
                    <div className="title">Professional Soundproofing
                    </div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="title">High-Quality Microphones
                    </div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                  <div className="item">
                    <div className="title">On-Demand Support</div>
                    <div className="percentage_container">
                      <span></span>
                      <span></span>
                      <span></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="section_four">
            <div className="part_one">
              <div className="wrapper">
                <h3 className="title">
                A Space to Create Without Limits
                </h3>
                <p className="sub_title">
                
<strong>Solo Podcasters:</strong> Enjoy a quiet, distraction-free environment equipped with top-notch audio equipment, ensuring your voice comes through crisp and clear.
</p>

<p className="sub_title">
<strong>Interview-Style Podcasts:</strong> Host engaging one-on-one conversations with ease, using our comfortable and fully equipped setup.
</p>

<p className="sub_title">
<strong>Panel Discussions:</strong> Accommodate multiple speakers effortlessly with our spacious layout, multiple microphones, and advanced audio-mixing technology.
</p>

<p className="sub_title">
<strong>Remote Guest Interviews:</strong> Seamlessly connect with guests from around the world using our high-speed internet and professional virtual setup tools.
</p>

<p className="sub_title">
No matter your podcasting format, our studio is built to make your creative process smooth and your content stand out.
</p>               
                {/* <div className="container">
                  <div className="item"></div>
                  <div className="item"></div>
                  <div className="item"></div>
                  <div className="item"></div>
                </div> */}
                {/* <button className="primay_button">Book Today</button> */}
              </div>
            </div>

            <div className="part_two"></div>
          </div>


            </div>

          </div>



          <div className="section_five">
            <div className="image"></div>
            <div className="title">Book Your Podcasting Experience</div>
            <div className="rate_container"></div>
            <div className="wrapper">
              <span> Choose Your Package </span>
              <span> Pick a Time Slot </span>
              <span> Confirm Your Booking </span>
            </div>
            <button className="primay_button"
                onClick={() => window.location.href = 'https://lumyn.setmore.com/'}

            >Book Now</button>
          </div>

          <div className="section_six">
            <h4 className="title">Transforming Ideas into Impactful Podcasts</h4>

            <div className="container">
              <div className="item">
                <Rating number={4} />
                <p className="testimonial">
                "The team at Lumyn made the entire process effortless.
                 From the moment I stepped into the studio, everything was perfectly set up.
                  My podcast has never sounded so professional!"
                </p>
                <p className="author">
                  Ernest Alford{" "}
                  <span className="designation">, Ui designer </span>
                </p>
              </div>
            </div>

            <div className="qoute">
              <svg
                width="184"
                height="151"
                viewBox="0 0 184 151"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  opacity="0.09"
                  d="M166.011 78.1583C178.004 78.1583 184 84.5704 184 97.3946V131.764C184 144.588 178.004 151 166.011 151H125.922C113.929 151 107.933 144.588 107.933 131.764V97.3946C107.933 75.3369 109.389 56.87 112.302 41.9939C115.214 26.9468 122.667 14.8065 134.659 5.57305C143.397 -1.09556 150.25 -1.77952 155.218 3.52117L164.983 14.0371C171.151 20.5347 170.209 26.9468 162.156 33.2734C156.674 37.5482 152.991 43.1053 151.106 49.9449C149.222 56.7845 148.279 66.189 148.279 78.1583H166.011ZM58.0782 78.1583C70.0708 78.1583 76.067 84.5704 76.067 97.3946V131.764C76.067 144.588 70.0708 151 58.0782 151H17.9888C5.99628 151 0 144.588 0 131.764V97.3946C0 75.3369 1.45624 56.87 4.36872 41.9939C7.28119 26.9468 14.7337 14.8065 26.7263 5.57305C35.4637 -1.09556 42.3166 -1.77952 47.2849 3.52117L57.0503 14.0371C63.2179 20.5347 62.2756 26.9468 54.2235 33.2734C48.7412 37.5482 45.0577 43.1053 43.1732 49.9449C41.2886 56.7845 40.3464 66.189 40.3464 78.1583H58.0782Z"
                  fill="white"
                />
              </svg>
            </div>
          </div>

          <div className="section_seven">
            <div className="container">
              <div className="part_one">
                {/* <div className="column">
                  <div className="item"></div>
                  <div className="item"></div>
                  <div className="item"></div>
                </div>
                <div className="column"></div>
                <div className="column"></div> */}
              </div>

              <div className="part_two">
                <h3 className="title">Follow Us @wearelumyn</h3>
                {/* <div className="team mobile"> */}
                {/* <p className="lumyn_text">@Team Lumyn</p> */}
                {/* </div> */}
              </div>
            </div>
          </div>

        </main>

        <Footer />
      </div>
    </>
  );
}
