import Head from "next/head";
import Image from "next/image";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

import Carousel from "react-multi-carousel";

export default function Products() {

  return (
    <>
      <Head>
        <title>Lumyn | Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <main className="main products">

          <div className="products_section">
            <NavMenuBar />
            <div className={"bredcrumb"}>
              <span>Home</span>
              <span>{">"}</span>
              <span className={"active"}>Product Details</span>
            </div>
            <div className="container">


              {/* <Carousel
                additionalTransfrom={0}
                arrows
                autoPlaySpeed={3000}
                centerMode={false}
                className=""
                containerClass=""
                dotListClass=""
                draggable
                focusOnSelect={false}
                infinite={true}
                itemClass=""
                keyBoardControl
                minimumTouchDrag={80}
                pauseOnHover
                renderArrowsWhenDisabled={false}
                renderButtonGroupOutside={false}
                renderDotsOutside={false}
                responsive={{
                  desktop: {
                    breakpoint: {
                      max: 3000,
                      min: 1024
                    },
                    items: 1,
                    partialVisibilityGutter: 30
                  },
                  mobile: {
                    breakpoint: {
                      max: 464,
                      min: 0
                    },
                    items: 1,
                    partialVisibilityGutter: 25
                  },
                  tablet: {
                    breakpoint: {
                      max: 1024,
                      min: 464
                    },
                    items: 1,
                    partialVisibilityGutter: 20
                  }
                }}
                rewind={false}
                rewindWithAnimation={false}
                rtl={false}
                shouldResetAutoplay
                showDots={true}
                sliderClass=""
                slidesToSlide={1}
                swipeable
              > */}


                {/* <div className="slide_container">
                  <div className="part_one">
                    <div className="image_container" >

                    </div>
                    <div className="discription">
                      <p className="content">
                        At Lumyn, we craft unique and compelling corporate brands that drive customer awareness and loyalty. Through consistent branding, we help build strong brand equity and credibility, ensuring your brand attracts investors and generates confidence. Our tailored strategies give you a competitive edge, enabling your business to stand out in a crowded marketplace. Whether you're looking to strengthen your brand's presence or expand into new markets, our solutions help you achieve long-term success. Let us help you create a brand that not only resonates with your audience but also fosters lasting relationships, customer loyalty, and much more.
                      </p>
                    </div>
                  </div>

                  <div className="part_two">

                    <h3 className="title"> Corporate Branding </h3>
                    <p className="sub_title"> Create a Brand That Stands the Test of Time! </p>

                    <div className="icon_highlight">
                      <div className="wrapper">
                        <Image src="/assets/svg/WWO Icons-01.svg" width={36} height={35} alt="map-point" />
                        Brand Development
                      </div>
                      <div className="wrapper">
                        <Image src="/assets/svg/WWO Icons-02.svg" width={36} height={35} alt="map-point" />
                        Identity Design
                      </div>
                      <div className="wrapper">
                        <Image src="/assets/svg/WWO Icons-03.svg" width={36} height={35} alt="map-point" />
                        Strategic Positioning
                      </div>
                    </div>

                    <div className="container_text">
                      <div className="item">Mastermind Team</div>
                      <div className="item">Strategic Vision</div>
                      <div className="item">Innovative Techniques</div>
                      <div className="item">Future-Proof Solutions</div>
                      <div className="item">Real-Time Monitoring</div>
                      <div className="item">Goal-Crushing Focus</div>
                    </div>

                    <p className="extra_descirption mobile">
                      Vestibulum ante ipsum primis in
                      faucibus orci luctus ultrices posuere
                      cubilia curae; Vestibulum dictum
                    </p>

                    <button className="primay_button">
                      Contact Us
                    </button>
                  </div>

                  <div className="pricing_section"> <h3 className="pricing_title">Pricing</h3> <div className="pricing_item">Basic Plan: $100/month</div> <div className="pricing_item">Premium Plan: $200/month</div> <div className="pricing_item">Enterprise Plan: $500/month</div> </div>
                </div> */}

              <div className="slide_container">
                <div className="content_row">
                  <div className="part_one">
                  <div className="image_container">
  <Image src="/assets/images/product_images/WebCommerce.webp" alt="Description of the image"  width="500" height="500" />
</div>


                    
                  </div>
                  <div className="part_two">
                    <h3 className="title">LumaCommerce </h3>
                    <p className="sub_title">Your Digital Gateway to Success!</p>
                   
                    <div className="container_text">
                      <div className="item">WebsiteDevelopment</div>
                      <div className="item">WebDesign</div>
                      <div className="item">ECommerce</div>
                      <div className="item">CustomWebsites</div>
                      <div className="item">ResponsiveDesign</div>
                      {/* <div className="item">Goal-Crushing Focus</div> */}
                    </div>
                    {/* <p className="extra_description mobile">
                    Build a stunning and functional online presence with WebCommerce. Our tailored website packages include responsive designs, seamless e-commerce integration, and cutting-edge functionality to help your business thrive in the digital world.
                    </p> */}
                     <div className="description">
                      <p className="content">
                      Build a stunning and functional online presence with Luma Commerce. Our tailored website packages include responsive designs, seamless e-commerce integration, and cutting-edge functionality to help your business thrive in the digital world.
                      </p>
                    </div>
                    <button className="primay_button">Contact Us</button>
                  </div>
                </div>
               
                <div className="pricing_section">
                  <section className="pricing-plans">
                  {/* <Carousel
                additionalTransfrom={0}
                arrows
                autoPlaySpeed={3000}
                centerMode={false}
                className=""
                containerClass=""
                dotListClass=""
                draggable
                focusOnSelect={false}
                infinite={true}
                itemClass=""
                keyBoardControl
                minimumTouchDrag={80}
                pauseOnHover
                renderArrowsWhenDisabled={false}
                renderButtonGroupOutside={false}
                renderDotsOutside={false}
                responsive={{
                  desktop: {
                    breakpoint: {
                      max: 3000,
                      min: 1024
                    },
                    items: 1,
                    partialVisibilityGutter: 30
                  },
                  mobile: {
                    breakpoint: {
                      max: 464,
                      min: 0
                    },
                    items: 1,
                    partialVisibilityGutter: 25
                  },
                  tablet: {
                    breakpoint: {
                      max: 1024,
                      min: 464
                    },
                    items: 1,
                    partialVisibilityGutter: 20
                  }
                }}
                rewind={false}
                rewindWithAnimation={false}
                rtl={false}
                shouldResetAutoplay
                showDots={true}
                sliderClass=""
                slidesToSlide={1}
                swipeable
              >
                <div className="slide_container"> */}
                          <div className="pricing-card basic">
                            <div className="heading">
                              <h4>BASIC</h4>
                              <p>for basic websites </p>
                            </div>
                            <p className="price">
                             AED 1625
                              <sub></sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Up to 4 Pages</strong>(Home, About, Services, Contact)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Mobile</strong> Responsive Design
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>SEO </strong>-Basic Setup

                              </li>
                              {/* <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>1 MySQL</strong> database
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>5 email</strong> accounts
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>cPanel</strong> control panel
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Free SSL</strong> certificate
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>24/7</strong> support
                              </li> */}
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card standard">
                            <div className="heading">
                              <h4>STANDARD</h4>
                              <p>for medium-sized businesses </p>
                            </div>
                            <p className="price">
                             AED 3250
                              <sub></sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Up to 6 Pages</strong>
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Custom</strong> Design with Animations

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Contact </strong>Forms &<strong>Google</strong>Maps Integration
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Blog</strong> Section Setup

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>SEO +</strong>  Speed Optimization
                              </li>
                              {/* <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>cPanel</strong> control panel
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Free SSL</strong> certificate
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>24/7</strong> support
                              </li> */}
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card premium">
                            <div className="heading">
                              <h4>PREMIUM</h4>
                              <p>for E-Commerce Websites</p>
                            </div>
                            <p className="price">
                            AED 5410
                              <sub></sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Product Uploads</strong> (Up to 100 Products)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> Payment </strong>Gateway Integration
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>User </strong> Accounts & Wishlist Features
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Free</strong> First Year  Maintenance
                              </li>
                              {/* <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Unlimited email</strong> accounts
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>cPanel</strong> control panel
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Free SSL</strong> certificate
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>24/7 priority</strong> support
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Advanced</strong> security features
                              </li> */}
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          {/* </div></Carousel> */}
                  </section>
                </div>

              </div>
              <div className="slide_container">
                <div className="content_row">
                  <div className="part_one">
                    <div className="image_container">
                    <Image src="/assets/images/product_images/MarketBlaze.webp" alt="product_image_2" height="600" width="700"/>
                    </div>
                    {/* <div className="description">
                      <p className="content">
                      Dominate search engines with OptiRank. Our expert SEO packages boost your website’s rankings, increase organic traffic, and enhance visibility to ensure your business stays ahead in the digital landscape.
                      </p>
                    </div> */}
                  </div>
                  <div className="part_two">
                    <h3 className="title">LumaSpark </h3>
                    <p className="sub_title">Climb Higher, Stay Visible!</p>
                    {/* <div className="icon_highlight">
                      <div className="wrapper">
                        <Image
                          src="/assets/svg/WWO Icons-01.svg"
                          width={36}
                          height={35}
                          alt="map-point"
                        />
                        Brand Development
                      </div>
                      <div className="wrapper">
                        <Image
                          src="/assets/svg/WWO Icons-02.svg"
                          width={36}
                          height={35}
                          alt="map-point"
                        />
                        Identity Design
                      </div>
                      <div className="wrapper">
                        <Image
                          src="/assets/svg/WWO Icons-03.svg"
                          width={36}
                          height={35}
                          alt="map-point"
                        />
                        Strategic Positioning
                      </div>
                    </div> */}
                    <div className="container_text">
                      <div className="item">SEO</div>
                      <div className="item">SearchEngineOptimization</div>
                      <div className="item">GoogleRankings</div>
                      <div className="item">DigitalMarketing</div>
                      <div className="item">BoostTraffic</div>
                      {/* <div className="item">Goal-Crushing Focus</div> */}
                    </div>
                    <p className="extra_description mobile">
                      {/* Vestibulum ante ipsum primis in faucibus orci luctus... */}
                    </p>
                    <div className="description">
                      <p className="content">
                      Dominate search engines with LumaSpark. Our expert SEO packages boost your website’s rankings, increase organic traffic, and enhance visibility to ensure your business stays ahead in the digital landscape.
                      </p>
                    </div>
                    <button className="primay_button">Contact Us</button>
                  </div>
                </div>
                <div className="pricing_section">
                  <section className="pricing-plans">
                          <div className="pricing-card basic">
                            <div className="heading">
                              <h4>BASIC</h4>
                              <p>Basic SEO</p>
                            </div>
                            <p className="price">
                            AED 1085
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Keyword</strong> Research & Implementation
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>On-Page </strong> Optimization (5 Pages)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>100GB </strong>of bandwidth
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> Monthly </strong>SEO Report
                              </li>
                              {/* <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>5 email</strong> accounts
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>cPanel</strong> control panel
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Free SSL</strong> certificate
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>24/7</strong> support
                              </li> */}
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card standard">
                            <div className="heading">
                              <h4>STANDARD</h4>
                              <p>Advanced Seo</p>
                            </div>
                            <p className="price">
                            AED 1620
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Keyword</strong> Research &<strong>Competitor</strong> Analysis
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> On-Page </strong>Optimization (10 Pages)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                               <strong>Off-Page </strong>Optimization(Link Building, Directory Submissions)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Technical SEO </strong>
                                (Site Speed, Mobile Optimization)

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Monthly </strong>Reporting with Insights
                              </li>
                            
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card premium">
                            <div className="heading">
                              <h4>PREMIUM</h4>
                              <p>Premium SEO</p>
                            </div>
                            <p className="price">
                            AED 2699
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Full SEO Suite </strong>(On-Page, Off-Page, Technical)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Content Optimization </strong>(Blog Posts & Articles)

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Local SEO</strong>(Google My Business Optimization)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Performance</strong>-Monthly Reports with Strategy Suggestions

                              </li>
                              
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                  </section>
                </div>

              </div>
              <div className="slide_container">
                <div className="content_row">
                  <div className="part_one">
                    <div className="image_container">
                      <Image src="/assets/images/product_images/InsightMedia.webp" alt="product_image_3" width="700" height="600"/>
                    </div>
                    
                  </div>
                  <div className="part_two">
                    <h3 className="title">LumaSocial </h3>
                    <p className="sub_title">Turn Likes into Loyal Customers!</p>
                    {/* <div className="icon_highlight">
                      <div className="wrapper">
                        <Image
                          src="/assets/svg/WWO Icons-01.svg"
                          width={36}
                          height={35}
                          alt="map-point"
                        />
                        Brand Development
                      </div>
                      <div className="wrapper">
                        <Image
                          src="/assets/svg/WWO Icons-02.svg"
                          width={36}
                          height={35}
                          alt="map-point"
                        />
                        Identity Design
                      </div>
                      <div className="wrapper">
                        <Image
                          src="/assets/svg/WWO Icons-03.svg"
                          width={36}
                          height={35}
                          alt="map-point"
                        />
                        Strategic Positioning
                      </div>
                    </div> */}
                    <div className="container_text">
                      <div className="item">SocialMediaMarketing</div>
                      <div className="item">SMM</div>
                      <div className="item">SocialEngagement</div>
                      <div className="item">DigitalGrowth</div>
                      <div className="item">BrandAwareness</div>
                      {/* <div className="item">Goal-Crushing Focus</div> */}
                    </div>
                    <p className="extra_description mobile">
                      {/* Vestibulum ante ipsum primis in faucibus orci luctus... */}
                    </p>
                    <div className="description">
                      <p className="content">
                        Transform your social media channels into powerful marketing tools with InsightMedia. From engaging content creation to brand awareness strategies, our packages are designed to drive meaningful connections and measurable growth.
                      </p>
                    </div>
                    <button className="primay_button">Contact Us</button>
                  </div>
                </div>
                <div className="pricing_section">
                  <section className="pricing-plans">
                          <div className="pricing-card basic">
                            <div className="heading">
                              <h4>STARTER</h4>
                              <p>(Ideal for Small Businesses)</p>
                            </div>
                            <p className="price">
                            AED 2160
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Account </strong>Setup & Optimization(1-2 platforms)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>3 Static Posts</strong> per Month(Graphics + Captions + Editing)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>3 Video/Reel </strong> per Month

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Calendar</strong> Content Creation
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Basic</strong> Performance Report (Monthly)
                              </li>
                              
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card standard">
                            <div className="heading">
                              <h4>GROWTH</h4>
                              <p>for Growing Brands</p>
                            </div>
                            <p className="price">
                            AED 2599
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Account</strong> Setup & Optimization (2-4 platforms)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>6 Static Posts</strong> per Month (Graphics + Captions + Editing)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> 4 Video/Reel </strong> per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>4-6 Stories</strong>  per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Basic Engagement</strong>(Responding to Comments & DMs)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> Calendar</strong>Content Creation
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> Performance</strong>-Monthly Report
                              </li>
                             
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card premium">
                            <div className="heading">
                              <h4>PRO</h4>
                              <p>for Established Businesses</p>
                            </div>
                            <p className="price">
                            AED 4105
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Account</strong> Setup & Optimization (Up to 4 platforms)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>8 Static Posts</strong>  per Month (Graphics + Captions + Editing)

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>6 Video/Reel</strong> per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>8 Stories</strong> per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Basic Engagement</strong> (Comments & DMs)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>1 Video/Reel</strong>  per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Advanced Performance </strong> Report (Monthly Insights + Suggestions)
                              </li>
                              
                            
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card premium">
                            <div className="heading">
                              <h4>PREMIUM</h4>
                              <p>Comprehensive Social Media Management</p>
                            </div>
                            <p className="price">
                            AED 6478.92
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Account</strong>Setup & Optimization (Up to 6 platforms)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> 12 Static Posts</strong> per Month (Graphics, Captions, Hashtags, Editing)

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>8 Video/Reel</strong> per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>12 Stories</strong> per Month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Full Engagement</strong>  Management (Comments, DMs, Tag Monitoring)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Monthly Strategy Call</strong>   + Performance Report
                              </li>
              
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing-card premium">
                            <div className="heading">
                              <h4>CUSTOM</h4>
                              <p>Comprehensive Social Media Management</p>
                            </div>
                            <p>  Starting at </p>
                            <p className="price">
                            AED 2700
                              <sub>/month</sub>
                            </p>
                            <ul className="features">
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Paid Ad Campaign</strong> Management (Facebook, Instagram, LinkedIn, etc.)
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong> Influencer </strong>Collaboration Management

                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Event-Based</strong> Campaigns
                              </li>
                              {/* <p>Add on services</p>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Social Media Ad</strong>Starting at AED 1,080/month
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Video/Reel Editing</strong>- AED 540/Video
                              </li>
                              <li>
                                <i className="fa-solid fa-check"></i>
                                <strong>Influencer Campaign</strong>Starting at AED 1,625/Project
                              </li>
               */}
                            </ul>
                            <button className="cta-btn">CHOOSE PLAN</button>
                          </div>
                          <div className="pricing_section">
                                                   <h3 className="pricing_title" style={{ color: "#00ed85"}}>Add-On Services</h3> 
                                                   <div className="pricing_item">Social Media Ad Campaigns: Starting at AED 1,080/Monthly </div> 
                                                   <div className="pricing_item">Video/Reel Editing: AED 540/Video</div> 
                                                   <div className="pricing_item">Influencer Campaign Management: Starting at AED 1,625/Project</div>
                                                   
                                                    </div> 
                  </section>
                </div>

              </div>

              <div className="slide_container"> 
                <div className="content_row"> 
                  <div className="part_one"> 
                    <div className="image_container">
                    <Image src="/assets/images/product_images/BrandForge.webp" alt="product_image_4" width="700" height="600"/>
                      </div>
                          </div> <div className="part_two"> 
                            <h3 className="title"> LumaBrands </h3> 
                            <p className="sub_title"> Forge a Brand That Stands Out! </p>
                             {/* <div className="icon_highlight">
                               <div className="wrapper">
                                 <Image src="/assets/svg/WWO Icons-01.svg" width={36} height={35} alt="map-point" />
                                  Brand Development </div> <div className="wrapper"> 
                                    <Image src="/assets/svg/WWO Icons-02.svg" width={36} height={35} alt="map-point" />
                                     Identity Design </div>
                                     <div className="wrapper">
                                       <Image src="/assets/svg/WWO Icons-03.svg" width={36} height={35} alt="map-point" />
                                        Strategic Positioning </div>
                                         </div>  */}
                                         <div className="container_text"> 
                                          <div className="item">BrandIdentity </div>
                                           <div className="item">LogoDesign</div> 
                                           <div className="item">VisualBranding</div>
                                            <div className="item">BrandKit </div> 
                                            <div className="item">CreativeDesign</div> 
                                            {/* <div className="item">Goal-Crushing Focus</div>  */}
                                            </div>
                                            
                                             {/* <p className="extra_description mobile"> Vestibulum ante ipsum primis in faucibus orci luctus... </p> */}
                                             <div className="description">
                         <p className="content">Bring your brand to life with Luma Brands. Our branding packages include bespoke logo designs, cohesive brand kits, and creative solutions that build a lasting impression for your business. </p> 
                         </div>
                                              <button className="primay_button">Contact Us</button>
                                               </div> 
                                               </div>

                                                {/* <div className="pricing_section">
                                                   <h3 className="pricing_title">Pricing</h3> 
                                                   <div className="pricing_item">Basic Plan: $100/month</div> 
                                                   <div className="pricing_item">Premium Plan: $200/month</div> 
                                                   <div className="pricing_item">Enterprise Plan: $500/month</div>
                                                    </div>  */}

                                                    


                <div className="pricing_section">
                                  <section className="pricing-plans">
                                  <div className="pricing-card basic">
                                    <div className="heading">
                                      <h4>BASIC</h4>
                                      <p>Ideal for Startups</p>
                                    </div>
                                    <p className="price">
                                    AED 1620
                                      <sub></sub>
                                    </p>
                                    <ul className="features">
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Logo Design</strong> (3 Initial Concepts +1 Revision)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong> Basic Brand Color Palette</strong> (Primary & Secondary Colors)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Typography Guide  </strong>(Primary & Secondary Fonts)

                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong> Digital Assets</strong> (Business Card Design, Email Signature Design)
                                      </li>
                                      {/* <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>5 email</strong> accounts
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>cPanel</strong> control panel
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Free SSL</strong> certificate
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>24/7</strong> support
                                      </li> */}
                                    </ul>
                                    <button className="cta-btn">CHOOSE PLAN</button>
                                  </div>
                                  <div className="pricing-card standard">
                                    <div className="heading">
                                      <h4>STANDARD</h4>
                                      <p>For Growing Businesses</p>
                                    </div>
                                    <p className="price">
                                    AED 2699
                                      <sub></sub>
                                    </p>
                                    <ul className="features">
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong> Logo Design</strong> (5 Initial Concepts with 2 Revisions)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Brand Color Palette </strong> (Primary, Secondary & Tertiary Colors)

                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Typography Guide</strong> (Primary, Secondary Fonts, & Usage Guidelines)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Social Media Branding Kit</strong> (Profile Pictures, Cover Photos, Post)

                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Digital Assets </strong> (Business Card Design, Letterhead, Email Signature)

                                      </li>
                                      {/* <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>cPanel</strong> control panel
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Free SSL</strong> certificate
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>24/7</strong> support
                                      </li> */}
                                    </ul>
                                    <button className="cta-btn">CHOOSE PLAN</button>
                                  </div>
                                  <div className="pricing-card premium">
                                    <div className="heading">
                                      <h4>ADVANCED</h4>
                                      <p>For Established Brands</p>
                                    </div>
                                    <p className="price">
                                    AED 5399
                                      <sub></sub>
                                    </p>
                                    <ul className="features">
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong> Logo Design</strong> (5 Concepts & 5 Revisions)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Logo Animation </strong> (3 Concepts & 3 Revisions)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Comprehensive Brand Color Palette </strong> ( with Usage Guidelines)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Typography Guide </strong>(Fonts for Print, Web & Mobile)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Social Media Branding Kit </strong>(Profile Pictures, Cover Photos, Post & Story)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Digital & Print Assets</strong>  (Business Card, Letterhead, Invoice Template,
                               Email Signature)

                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Brand Guidelines Document</strong> (Logo Usage, Color & Font Guidelines,
                               Tone of Voice, Imagery Style)

                                      </li>
                                      
                                    </ul>
                                    <button className="cta-btn">CHOOSE PLAN</button>
                                  </div>
                                  <div className="pricing-card premium">
                                    <div className="heading">
                                      <h4>PREMIUM</h4>
                                      <p>Comprehensive Corporate Identity</p>
                                    </div>
                                    <p className="price">
                                    AED 8099
                                      <sub></sub>
                                    </p>
                                    <ul className="features">
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong> Logo Design</strong> (10 Concepts & 10 Revisions)

                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Logo Animation </strong> (5 Concepts & 5 Revisions)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Full Brand Identity System </strong> (Color Palette, Typography, Iconography)
                                      </li>
                                      
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Social Media Branding Kit </strong>(Profile Pictures, Cover Photos, Post & Story)
                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Digital & Print Assets</strong>  (Business Card, Letterhead, Invoice, Email
                                          Signature, Presentation Template)
                             

                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"></i>
                                        <strong>Brand Guidelines Document</strong>(Detailed Usage Guidelines + Brand
Messaging & Positioning)


                                      </li>
                                      <li>
                                        <i className="fa-solid fa-check"> </i>
                                        <strong>1 Brand Strategy </strong> Consultation Session
                             

                                      </li>
                                    </ul>
                                    <button className="cta-btn">CHOOSE PLAN</button>
                                  </div>
                                   <div className="pricing_section">
                                                   <h3 className="pricing_title" style={{ color: "#00ed85"}}>Add-On Services</h3> 
                                                   <div className="pricing_item">Packaging Design: Starting at AED 865/Design</div> 
                                                   <div className="pricing_item">Merch Design (T-Shirts, Mugs, etc.): Starting at AED 750</div> 
                                                   <div className="pricing_item">Social Media Launch Campaign: AED 1620</div>
                                                   <div className="pricing_item">Website Branding Integration: AED 2160</div>
                                                    </div> 

                                </section>
                            </div>
                            </div> 
                          
                {/* <div className="discription_mobile mobile">
                                            <h3 className="title">Description</h3>
                                            <p className="content">
                                            At Lumyn, we craft unique and compelling corporate brands that drive customer awareness and loyalty. Through consistent branding, we help build strong brand equity and credibility, ensuring your brand attracts investors and generates confidence. Our tailored strategies give you a competitive edge, enabling your business to stand out in a crowded marketplace. Whether you're looking to strengthen your brand's presence or expand into new markets, our solutions help you achieve long-term success. Let us help you create a brand that not only resonates with your audience but also fosters lasting relationships, customer loyalty, and much more.
                                            </p>
                                            <div className="bottom">
                                              <div className="wrapper">
                                              <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M19.1965 10.6924C19.1413 10.6646 19.086 10.6507 19.0302 10.6507C18.9102 10.6507 18.8045 10.6967 18.7123 10.7891L17.8271 11.6741C17.7444 11.7572 17.7028 11.8585 17.7028 11.9785V15.4911C17.7028 16.0998 17.4866 16.6205 17.053 17.0541C16.6196 17.4874 16.0986 17.704 15.49 17.704H3.98315C3.37453 17.704 2.85354 17.4874 2.42023 17.0541C1.98683 16.6206 1.77025 16.0999 1.77025 15.4911V3.9845C1.77025 3.37597 1.98683 2.85503 2.42023 2.42158C2.85354 1.98822 3.37453 1.77159 3.98315 1.77159H15.4901C15.693 1.77159 15.9004 1.79925 16.1125 1.85462C16.1678 1.87293 16.2093 1.88228 16.2366 1.88228C16.3567 1.88228 16.4627 1.83631 16.5549 1.74412L17.2326 1.06643C17.3431 0.955933 17.3848 0.822137 17.3569 0.665526C17.3292 0.517973 17.2461 0.411886 17.1078 0.347411C16.6103 0.117217 16.0706 0.00158691 15.4898 0.00158691H3.98315C2.88595 0.00158691 1.94774 0.391153 1.1686 1.17029C0.389567 1.94952 0 2.88759 0 3.98483V15.4918C0 16.5888 0.389567 17.527 1.16865 18.3061C1.94778 19.0855 2.886 19.475 3.9832 19.475H15.49C16.5871 19.475 17.5254 19.0855 18.3045 18.3061C19.0837 17.527 19.4736 16.5889 19.4736 15.4918V11.0934C19.4735 10.9 19.3809 10.7664 19.1965 10.6924Z" fill="white"/>
                                        <path d="M22.6681 2.75376L21.1466 1.23226C20.9253 1.01103 20.6623 0.900391 20.358 0.900391C20.054 0.900391 19.7909 1.01103 19.5698 1.23226L10.6214 10.1806L6.9842 6.5432C6.76287 6.32182 6.50002 6.21132 6.19586 6.21132C5.89165 6.21132 5.6289 6.32182 5.40752 6.5432L3.88622 8.0645C3.66494 8.28578 3.5542 8.54863 3.5542 8.85298C3.5542 9.1572 3.66494 9.41994 3.88622 9.64132L9.83323 15.5883C10.0546 15.8098 10.3174 15.9202 10.6216 15.9202C10.9257 15.9202 11.1885 15.8098 11.4099 15.5883L22.6679 4.33039C22.889 4.10916 22.9999 3.84626 22.9999 3.54205C22.9999 3.23784 22.8893 2.975 22.6681 2.75376Z" fill="#00EC84"/>
                                      </svg>

                                          <span className="text">Mauris varius</span>
                                              </div>
                                              <div className="wrapper">
                                              <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M19.1965 10.6924C19.1413 10.6646 19.086 10.6507 19.0302 10.6507C18.9102 10.6507 18.8045 10.6967 18.7123 10.7891L17.8271 11.6741C17.7444 11.7572 17.7028 11.8585 17.7028 11.9785V15.4911C17.7028 16.0998 17.4866 16.6205 17.053 17.0541C16.6196 17.4874 16.0986 17.704 15.49 17.704H3.98315C3.37453 17.704 2.85354 17.4874 2.42023 17.0541C1.98683 16.6206 1.77025 16.0999 1.77025 15.4911V3.9845C1.77025 3.37597 1.98683 2.85503 2.42023 2.42158C2.85354 1.98822 3.37453 1.77159 3.98315 1.77159H15.4901C15.693 1.77159 15.9004 1.79925 16.1125 1.85462C16.1678 1.87293 16.2093 1.88228 16.2366 1.88228C16.3567 1.88228 16.4627 1.83631 16.5549 1.74412L17.2326 1.06643C17.3431 0.955933 17.3848 0.822137 17.3569 0.665526C17.3292 0.517973 17.2461 0.411886 17.1078 0.347411C16.6103 0.117217 16.0706 0.00158691 15.4898 0.00158691H3.98315C2.88595 0.00158691 1.94774 0.391153 1.1686 1.17029C0.389567 1.94952 0 2.88759 0 3.98483V15.4918C0 16.5888 0.389567 17.527 1.16865 18.3061C1.94778 19.0855 2.886 19.475 3.9832 19.475H15.49C16.5871 19.475 17.5254 19.0855 18.3045 18.3061C19.0837 17.527 19.4736 16.5889 19.4736 15.4918V11.0934C19.4735 10.9 19.3809 10.7664 19.1965 10.6924Z" fill="white"/>
                                            <path d="M22.6681 2.75376L21.1466 1.23226C20.9253 1.01103 20.6623 0.900391 20.358 0.900391C20.054 0.900391 19.7909 1.01103 19.5698 1.23226L10.6214 10.1806L6.9842 6.5432C6.76287 6.32182 6.50002 6.21132 6.19586 6.21132C5.89165 6.21132 5.6289 6.32182 5.40752 6.5432L3.88622 8.0645C3.66494 8.28578 3.5542 8.54863 3.5542 8.85298C3.5542 9.1572 3.66494 9.41994 3.88622 9.64132L9.83323 15.5883C10.0546 15.8098 10.3174 15.9202 10.6216 15.9202C10.9257 15.9202 11.1885 15.8098 11.4099 15.5883L22.6679 4.33039C22.889 4.10916 22.9999 3.84626 22.9999 3.54205C22.9999 3.23784 22.8893 2.975 22.6681 2.75376Z" fill="#00EC84"/>
                                        </svg>

                                        <span className="text">Mauris varius</span>
                                              </div>

                                              <div className="wrapper">
                                              <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M19.1965 10.6924C19.1413 10.6646 19.086 10.6507 19.0302 10.6507C18.9102 10.6507 18.8045 10.6967 18.7123 10.7891L17.8271 11.6741C17.7444 11.7572 17.7028 11.8585 17.7028 11.9785V15.4911C17.7028 16.0998 17.4866 16.6205 17.053 17.0541C16.6196 17.4874 16.0986 17.704 15.49 17.704H3.98315C3.37453 17.704 2.85354 17.4874 2.42023 17.0541C1.98683 16.6206 1.77025 16.0999 1.77025 15.4911V3.9845C1.77025 3.37597 1.98683 2.85503 2.42023 2.42158C2.85354 1.98822 3.37453 1.77159 3.98315 1.77159H15.4901C15.693 1.77159 15.9004 1.79925 16.1125 1.85462C16.1678 1.87293 16.2093 1.88228 16.2366 1.88228C16.3567 1.88228 16.4627 1.83631 16.5549 1.74412L17.2326 1.06643C17.3431 0.955933 17.3848 0.822137 17.3569 0.665526C17.3292 0.517973 17.2461 0.411886 17.1078 0.347411C16.6103 0.117217 16.0706 0.00158691 15.4898 0.00158691H3.98315C2.88595 0.00158691 1.94774 0.391153 1.1686 1.17029C0.389567 1.94952 0 2.88759 0 3.98483V15.4918C0 16.5888 0.389567 17.527 1.16865 18.3061C1.94778 19.0855 2.886 19.475 3.9832 19.475H15.49C16.5871 19.475 17.5254 19.0855 18.3045 18.3061C19.0837 17.527 19.4736 16.5889 19.4736 15.4918V11.0934C19.4735 10.9 19.3809 10.7664 19.1965 10.6924Z" fill="white"/>
                                        <path d="M22.6681 2.75376L21.1466 1.23226C20.9253 1.01103 20.6623 0.900391 20.358 0.900391C20.054 0.900391 19.7909 1.01103 19.5698 1.23226L10.6214 10.1806L6.9842 6.5432C6.76287 6.32182 6.50002 6.21132 6.19586 6.21132C5.89165 6.21132 5.6289 6.32182 5.40752 6.5432L3.88622 8.0645C3.66494 8.28578 3.5542 8.54863 3.5542 8.85298C3.5542 9.1572 3.66494 9.41994 3.88622 9.64132L9.83323 15.5883C10.0546 15.8098 10.3174 15.9202 10.6216 15.9202C10.9257 15.9202 11.1885 15.8098 11.4099 15.5883L22.6679 4.33039C22.889 4.10916 22.9999 3.84626 22.9999 3.54205C22.9999 3.23784 22.8893 2.975 22.6681 2.75376Z" fill="#00EC84"/>
                                        </svg>

                                      <span className="text">Mauris varius</span>
                                              </div>

                                            </div>
                                      </div> */}

             
                        {/* <div className="slide_container">

                          <div className="part_one">
                            <div className="image_container" >

                            </div>
                            <div className="discription">
                              <p className="content">
                                At Lumyn, we craft unique and compelling corporate brands that drive customer awareness and loyalty. Through consistent branding, we help build strong brand equity and credibility, ensuring your brand attracts investors and generates confidence. Our tailored strategies give you a competitive edge, enabling your business to stand out in a crowded marketplace. Whether you're looking to strengthen your brand's presence or expand into new markets, our solutions help you achieve long-term success. Let us help you create a brand that not only resonates with your audience but also fosters lasting relationships, customer loyalty, and much more.
                              </p>
                            </div>
                          </div>

                          <div className="part_two">

                            <h3 className="title"> Corporate Branding </h3>
                            <p className="sub_title"> Create a Brand That Stands the Test of Time! </p>

                            <div className="icon_highlight">
                              <div className="wrapper">
                                <Image src="/assets/svg/WWO Icons-01.svg" width={36} height={35} alt="map-point" />
                                Brand Development
                              </div>
                              <div className="wrapper">
                                <Image src="/assets/svg/WWO Icons-02.svg" width={36} height={35} alt="map-point" />
                                Identity Design
                              </div>
                              <div className="wrapper">
                                <Image src="/assets/svg/WWO Icons-03.svg" width={36} height={35} alt="map-point" />
                                Strategic Positioning
                              </div>
                            </div>

                            <div className="container_text">
                              <div className="item">Mastermind Team</div>
                              <div className="item">Strategic Vision</div>
                              <div className="item">Innovative Techniques</div>
                              <div className="item">Future-Proof Solutions</div>
                              <div className="item">Real-Time Monitoring</div>
                              <div className="item">Goal-Crushing Focus</div>
                            </div>

                            <p className="extra_descirption mobile">
                              Vestibulum ante ipsum primis in
                              faucibus orci luctus ultrices posuere
                              cubilia curae; Vestibulum dictum
                            </p>

                            <button className="primay_button">
                              Contact Us
                            </button>
                          </div>

                          <div className="discription_mobile mobile">
                            <h3 className="title">Description</h3>
                            <p className="content">
                              At Lumyn, we craft unique and compelling corporate brands that drive customer awareness and loyalty. Through consistent branding, we help build strong brand equity and credibility, ensuring your brand attracts investors and generates confidence. Our tailored strategies give you a competitive edge, enabling your business to stand out in a crowded marketplace. Whether you're looking to strengthen your brand's presence or expand into new markets, our solutions help you achieve long-term success. Let us help you create a brand that not only resonates with your audience but also fosters lasting relationships, customer loyalty, and much more.
                            </p>
                            <div className="bottom">
                              <div className="wrapper">
                                <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M19.1965 10.6924C19.1413 10.6646 19.086 10.6507 19.0302 10.6507C18.9102 10.6507 18.8045 10.6967 18.7123 10.7891L17.8271 11.6741C17.7444 11.7572 17.7028 11.8585 17.7028 11.9785V15.4911C17.7028 16.0998 17.4866 16.6205 17.053 17.0541C16.6196 17.4874 16.0986 17.704 15.49 17.704H3.98315C3.37453 17.704 2.85354 17.4874 2.42023 17.0541C1.98683 16.6206 1.77025 16.0999 1.77025 15.4911V3.9845C1.77025 3.37597 1.98683 2.85503 2.42023 2.42158C2.85354 1.98822 3.37453 1.77159 3.98315 1.77159H15.4901C15.693 1.77159 15.9004 1.79925 16.1125 1.85462C16.1678 1.87293 16.2093 1.88228 16.2366 1.88228C16.3567 1.88228 16.4627 1.83631 16.5549 1.74412L17.2326 1.06643C17.3431 0.955933 17.3848 0.822137 17.3569 0.665526C17.3292 0.517973 17.2461 0.411886 17.1078 0.347411C16.6103 0.117217 16.0706 0.00158691 15.4898 0.00158691H3.98315C2.88595 0.00158691 1.94774 0.391153 1.1686 1.17029C0.389567 1.94952 0 2.88759 0 3.98483V15.4918C0 16.5888 0.389567 17.527 1.16865 18.3061C1.94778 19.0855 2.886 19.475 3.9832 19.475H15.49C16.5871 19.475 17.5254 19.0855 18.3045 18.3061C19.0837 17.527 19.4736 16.5889 19.4736 15.4918V11.0934C19.4735 10.9 19.3809 10.7664 19.1965 10.6924Z" fill="white" />
                                  <path d="M22.6681 2.75376L21.1466 1.23226C20.9253 1.01103 20.6623 0.900391 20.358 0.900391C20.054 0.900391 19.7909 1.01103 19.5698 1.23226L10.6214 10.1806L6.9842 6.5432C6.76287 6.32182 6.50002 6.21132 6.19586 6.21132C5.89165 6.21132 5.6289 6.32182 5.40752 6.5432L3.88622 8.0645C3.66494 8.28578 3.5542 8.54863 3.5542 8.85298C3.5542 9.1572 3.66494 9.41994 3.88622 9.64132L9.83323 15.5883C10.0546 15.8098 10.3174 15.9202 10.6216 15.9202C10.9257 15.9202 11.1885 15.8098 11.4099 15.5883L22.6679 4.33039C22.889 4.10916 22.9999 3.84626 22.9999 3.54205C22.9999 3.23784 22.8893 2.975 22.6681 2.75376Z" fill="#00EC84" />
                                </svg>

                                <span className="text">Mauris varius</span>
                              </div>
                              <div className="wrapper">
                                <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M19.1965 10.6924C19.1413 10.6646 19.086 10.6507 19.0302 10.6507C18.9102 10.6507 18.8045 10.6967 18.7123 10.7891L17.8271 11.6741C17.7444 11.7572 17.7028 11.8585 17.7028 11.9785V15.4911C17.7028 16.0998 17.4866 16.6205 17.053 17.0541C16.6196 17.4874 16.0986 17.704 15.49 17.704H3.98315C3.37453 17.704 2.85354 17.4874 2.42023 17.0541C1.98683 16.6206 1.77025 16.0999 1.77025 15.4911V3.9845C1.77025 3.37597 1.98683 2.85503 2.42023 2.42158C2.85354 1.98822 3.37453 1.77159 3.98315 1.77159H15.4901C15.693 1.77159 15.9004 1.79925 16.1125 1.85462C16.1678 1.87293 16.2093 1.88228 16.2366 1.88228C16.3567 1.88228 16.4627 1.83631 16.5549 1.74412L17.2326 1.06643C17.3431 0.955933 17.3848 0.822137 17.3569 0.665526C17.3292 0.517973 17.2461 0.411886 17.1078 0.347411C16.6103 0.117217 16.0706 0.00158691 15.4898 0.00158691H3.98315C2.88595 0.00158691 1.94774 0.391153 1.1686 1.17029C0.389567 1.94952 0 2.88759 0 3.98483V15.4918C0 16.5888 0.389567 17.527 1.16865 18.3061C1.94778 19.0855 2.886 19.475 3.9832 19.475H15.49C16.5871 19.475 17.5254 19.0855 18.3045 18.3061C19.0837 17.527 19.4736 16.5889 19.4736 15.4918V11.0934C19.4735 10.9 19.3809 10.7664 19.1965 10.6924Z" fill="white" />
                                  <path d="M22.6681 2.75376L21.1466 1.23226C20.9253 1.01103 20.6623 0.900391 20.358 0.900391C20.054 0.900391 19.7909 1.01103 19.5698 1.23226L10.6214 10.1806L6.9842 6.5432C6.76287 6.32182 6.50002 6.21132 6.19586 6.21132C5.89165 6.21132 5.6289 6.32182 5.40752 6.5432L3.88622 8.0645C3.66494 8.28578 3.5542 8.54863 3.5542 8.85298C3.5542 9.1572 3.66494 9.41994 3.88622 9.64132L9.83323 15.5883C10.0546 15.8098 10.3174 15.9202 10.6216 15.9202C10.9257 15.9202 11.1885 15.8098 11.4099 15.5883L22.6679 4.33039C22.889 4.10916 22.9999 3.84626 22.9999 3.54205C22.9999 3.23784 22.8893 2.975 22.6681 2.75376Z" fill="#00EC84" />
                                </svg>

                                <span className="text">Mauris varius</span>
                              </div>

                              <div className="wrapper">
                                <svg width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M19.1965 10.6924C19.1413 10.6646 19.086 10.6507 19.0302 10.6507C18.9102 10.6507 18.8045 10.6967 18.7123 10.7891L17.8271 11.6741C17.7444 11.7572 17.7028 11.8585 17.7028 11.9785V15.4911C17.7028 16.0998 17.4866 16.6205 17.053 17.0541C16.6196 17.4874 16.0986 17.704 15.49 17.704H3.98315C3.37453 17.704 2.85354 17.4874 2.42023 17.0541C1.98683 16.6206 1.77025 16.0999 1.77025 15.4911V3.9845C1.77025 3.37597 1.98683 2.85503 2.42023 2.42158C2.85354 1.98822 3.37453 1.77159 3.98315 1.77159H15.4901C15.693 1.77159 15.9004 1.79925 16.1125 1.85462C16.1678 1.87293 16.2093 1.88228 16.2366 1.88228C16.3567 1.88228 16.4627 1.83631 16.5549 1.74412L17.2326 1.06643C17.3431 0.955933 17.3848 0.822137 17.3569 0.665526C17.3292 0.517973 17.2461 0.411886 17.1078 0.347411C16.6103 0.117217 16.0706 0.00158691 15.4898 0.00158691H3.98315C2.88595 0.00158691 1.94774 0.391153 1.1686 1.17029C0.389567 1.94952 0 2.88759 0 3.98483V15.4918C0 16.5888 0.389567 17.527 1.16865 18.3061C1.94778 19.0855 2.886 19.475 3.9832 19.475H15.49C16.5871 19.475 17.5254 19.0855 18.3045 18.3061C19.0837 17.527 19.4736 16.5889 19.4736 15.4918V11.0934C19.4735 10.9 19.3809 10.7664 19.1965 10.6924Z" fill="white" />
                                  <path d="M22.6681 2.75376L21.1466 1.23226C20.9253 1.01103 20.6623 0.900391 20.358 0.900391C20.054 0.900391 19.7909 1.01103 19.5698 1.23226L10.6214 10.1806L6.9842 6.5432C6.76287 6.32182 6.50002 6.21132 6.19586 6.21132C5.89165 6.21132 5.6289 6.32182 5.40752 6.5432L3.88622 8.0645C3.66494 8.28578 3.5542 8.54863 3.5542 8.85298C3.5542 9.1572 3.66494 9.41994 3.88622 9.64132L9.83323 15.5883C10.0546 15.8098 10.3174 15.9202 10.6216 15.9202C10.9257 15.9202 11.1885 15.8098 11.4099 15.5883L22.6679 4.33039C22.889 4.10916 22.9999 3.84626 22.9999 3.54205C22.9999 3.23784 22.8893 2.975 22.6681 2.75376Z" fill="#00EC84" />
                                </svg>

                                <span className="text">Mauris varius</span>
                              </div>

                            </div>
                          </div>

                        </div> */}

              {/* </Carousel> */}








            </div>
          </div>

        </main>
        <Footer />
      </div>
    </>
  )
}