import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

export default function Products() {

    return(
        <>
        <Head>
          <title>Lumyn | Products</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="page">
            <main className="main products">

            <div className="products_section">
                <NavMenuBar/>
                <div className={"bredcrumb"}>
                    <span>Home</span>
                    <span>{">"}</span>
                    <span className={"active"}>Product Details</span>
                </div>
                <div className="container">
      
                </div>
            </div>

            </main>
            <Footer/>
        </div>
        </>
    )
}