import Head from "next/head";
import Image from "next/image";

import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";


export default function BlogDetails() {

    return(
        <>
        <Head>
          <title>Lumyn | Blog Deatils</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="page">
            <main className="main blog_details">

              <div className="blog_details_container">

                                <NavMenuBar />
                
                                <div className="bredcrumb">
                                    <span>Home</span>
                                    <span>{">"}</span>
                                    <span className="active">Blog</span>
                                    <span>{">"}</span>
                                    <span className="active">Detail</span>
                                </div>

                                <div className="blog_image">

                                </div>

                                <div className="blog_title_description">
                                  <div className="comments">by Admin  | 42 comments</div>
                                  <h3 className="title"> Domain Privacy Protection: Why It's Essential for Website Owners  </h3>
                                  <p className="description"> Domain privacy protection, also known as WHOIS privacy, is a service that shields your personal information from public view when you register a domain name. Without it, details like your name, address, phone number, and email are publicly accessible through WHOIS databases. </p>
                                </div>

                                <div className="section_image_description">

                                  <div className="image_container">

                                  </div>
                                  <div className="description_container">
                                    <h4 className="title">Why You Need Domain Privacy Protection </h4>
                                    <p className="description">
                                      Protection from Identity Theft Cybercriminals frequently scrape WHOIS data to gather personal information. Domain privacy protection prevents your sensitive data from falling into the wrong hands.</p>

                                    <h4 className="title">Spam Prevention</h4>
                                    <p>Public WHOIS information often leads to unwanted marketing calls, emails, and physical mail. Privacy protection significantly reduces spam by masking your contact details.</p>

                                    <h4 className="title">Business Privacy</h4>
                                    <p>For businesses, domain privacy protection helps maintain confidentiality around new projects and prevents competitors from gathering intelligence about your digital properties.</p>
                                  </div>

                                 </div>

                                <div className="section_quote">
                                <div className="section_quote_content">
                                 
                                             <img src="/assets/png/quotes.png" alt="Quote Icon" className="image_container"/>
                                            <div className="divider"></div>
                                            <p className="title"> "It's Only for Large Businesses"
                                            Domain privacy is valuable for everyone - from individual bloggers to large corporations. Personal information needs protection regardless of website size.
                                           </p>
                                            </div> 
                                </div>

                                <div className="section_image_description">

                                <div className="description_container padding">
                                    <h4 className="title">How Domain Privacy Protection Works</h4>
                                    <p className="description">When you purchase domain privacy, your registrar replaces your personal information with generic company details or proxy information in the WHOIS database. This creates a protective barrier while maintaining compliance with ICANN regulations.</p>

                                <h4 className="title">The Cost Factor</h4>

                               <p>Most registrars charge $10-15 annually for domain privacy protection. Some providers include it free with domain registration. Consider this small investment against the potential costs of identity theft or spam management.</p>
                                </div>
                                <div className="image_container">

                                </div>
                               
                                </div>
                                <div className="blog_title_description">
                                  
                                  <h4 className="title"> Conclusion </h4>
                                  <p className="description">In today's digital landscape, domain privacy protection isn't just an option—it's a necessity. Consider it an essential component of your online security strategy rather than an optional add-on.</p>
                                </div>

                               <div className="section_bottom">
                                <div className="social_media_container">

                                  <div className="tags"> 
                                    Tags:
                                    <span>Domain Privacy</span>
                                    <span>WHOIS privacy</span>
                                    <span>Cybersecurity</span>
                                  </div>



                                          <div className="social_media">
                                            <Image
                                              src="/assets/svg/facebook.svg"
                                              alt="facebook-logo"
                                              width={20}
                                              height={20}
                                            />
                                            <Image
                                              src="/assets/svg/instagram.svg"
                                              alt="instagram-logo"
                                              width={20}
                                              height={20}
                                            />
                                            <Image
                                              src="/assets/svg/twitter.svg"
                                              alt="twitter-logo"
                                              width={20}
                                              height={20}
                                            />
                                          </div>

                                </div>
                                <div className="navigation">

                                  <div className="previouse">
                                    <div className="blog_image">12</div>

                                    <div className="content_container">
                                    <p className="top">
by Admin  | 42 comments
                                      </p>
                                      <h3 className="title">
                                      Cruising into the Future Electric Scooters
                                      </h3>
                                      <span> <svg width="20" height="13" viewBox="0 0 20 13" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0.185385 6.89351L6.7834 12.3786C7.0042 12.562 7.33448 12.535 7.52092 12.3179C7.70763 12.1007 7.67993 11.7759 7.45913 11.5925L1.95315 7.01532H18.9766C19.2656 7.01532 19.5 6.7848 19.5 6.50057C19.5 6.21635 19.2656 5.98583 18.9766 5.98583H1.95341L7.45939 1.40865C7.6802 1.22502 7.7079 0.900452 7.52119 0.68329C7.41758 0.562789 7.27002 0.500705 7.12113 0.500705C7.00181 0.500705 6.88168 0.540523 6.7834 0.622253L0.185385 6.10738C0.0676575 6.20509 -0.000263214 6.3489 -0.000263214 6.50057C-0.000263214 6.65225 0.0676575 6.7958 0.185385 6.89377V6.89351Z" fill="white"/>
</svg> Previous</span>
                                    </div>

                                  </div>

                                  <div className="next">
                                  <div className="blog_image">

                                  </div>
                                  <div className="content_container">
                                      <p className="top">
by Admin  | 42 comments
                                      </p>
                                      <h3 className="title">
                                      Cruising into the Future Electric Scooters
                                      </h3>
                                      <span> 
                                         Next
                                         <svg width="20" height="13" viewBox="0 0 20 13" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M19.3146 6.89351L12.7166 12.3786C12.4958 12.562 12.1655 12.535 11.9791 12.3179C11.7924 12.1007 11.8201 11.7759 12.0409 11.5925L17.5469 7.01532H0.523377C0.234388 7.01532 0 6.7848 0 6.50057C0 6.21635 0.234388 5.98583 0.523377 5.98583H17.5466L12.0406 1.40865C11.8198 1.22502 11.7921 0.900452 11.9788 0.68329C12.0824 0.562789 12.23 0.500705 12.3789 0.500705C12.4982 0.500705 12.6183 0.540523 12.7166 0.622253L19.3146 6.10738C19.4323 6.20509 19.5003 6.3489 19.5003 6.50057C19.5003 6.65225 19.4323 6.7958 19.3146 6.89377V6.89351Z" fill="white"/>
</svg>

                                         
                                         </span>
                                  </div>
                                  </div>

                                </div>
                              </div>



            
              </div>

            </main>
        <Footer/>
        </div>
        </>
        )
}