import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

export default function Blogs() {

    return(
        <>
        <Head>
          <title>Lumyn | Blogs</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="page">
        <main className="main blogs">
            <div className="blog_section">
                <NavMenuBar />

                <div className="bredcrumb">
                    <span>Home</span>
                    <span>{">"}</span>
                    <span className="active">Blogs</span>
                </div>

                <div className="container">
                    <div className="blog_item">
                        <div className="image"></div>
                        <p className="comment"> by Admin | 42 comments </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </div>

                    <div className="blog_item">
                        <div className="image"></div>
                        <p className="comment"> by Admin | 42 comments </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </div>
                </div>

                <div className="container">
                    <div className="blog_item">
                        <div className="image"></div>
                        <p className="comment"> by Admin | 42 comments </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </div>

                    <div className="blog_item">
                        <div className="image"></div>
                        <p className="comment"> by Admin | 42 comments </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </div>
                </div>

                <div className="container">
                    <div className="blog_item">
                        <div className="image"></div>
                        <p className="comment"> by Admin | 42 comments </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </div>

                    <div className="blog_item">
                        <div className="image"></div>
                        <p className="comment"> by Admin | 42 comments </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </div>
                </div>
            </div>
            <div className="pagination_section">
                <span className="active">1</span>
                <span>2</span>
                <span>3</span>
                <span className="next">Next</span>
            </div>
        </main>

            <Footer/>
        </div>
        </>
    )
}