import Head from "next/head";
import Footer from "@/component/footer";
import NavMenuBar from "@/component/menu";

export default function Blogs() {
    const timelineData = [
        { year: "2022", title: "Team Lumyn", desc: "Driving Organic Traffic: Essential Strategies for 2025", icon: "/assets/images/blog_images/Driving_Organic_Traffic.jpeg", link:"/blogs/driving-organic-traffic-strategies" },
        { year: "2017", title: "Team Lumyn", desc: "Domain Privacy Protection: Why It's Essential for Website Owners", icon: "/assets/images/blog_images/Domain_Privacy.jpeg", link:"/blogs/need-for-domain-privacy-protection" },
        { year: "2012", title: "Team Lumyn", desc: " Website Revamping: A Strategic Approach to Business Growth", icon: "/assets/images/blog_images/Website_Revamping.jpeg", link:"/blogs/website-revamping" },
        // { year: "2007", title: "ULLAMCROPER", desc: "Ullamcorper suscipit labor tis nisl ut aliquip ex ea commodo.", icon: "/assets/images/Customease.webp", link:"#" },
        // { year: "2002", title: "LOREM IPSUM", desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", icon: "/assets/images/Customease.webp", link:"#" },
      ];

    return(
        <>
        <Head>
          <title>Lumyn | Blogs </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="page">
        <main className="main blogs">
            <div className="blog_section">
                <NavMenuBar />

                <div className="bredcrumb">
                    <span>Home</span>
                    <span>{">"}</span>
                    <span className="active">Blogs</span>
                </div>
                <div className="tree_section">
                <div className="treeContainer">
      {/* <div className="treeTitle">TREE INFOGRAPHIC</div> */}
        {/* <div className="content">
              <div className="icon">{item.icon}</div> */}


      <div className="tree">
        {timelineData.map((item, index) => (
          <div key={index} className={`${"branch"} ${index % 2 === 0 ? "left" : "right" }`}>
          
               <div className="content">
            <div className="icon">
              <img src={item.icon} alt={item.title} />
            </div>
              <h3>{item.title}</h3>
              <p>
              <a href={item.link}>
                {item.desc}
                </a>
                </p>
            </div>
          </div>
        ))

        }
      </div>
      <div className="tree tree_mobile">
        {timelineData.map((item, index) => (
          <div key={index} className="branch left">
            {/* <div className="content">
              <div className="icon">{item.icon}</div> */}
               <div className="content">
            <div className="icon">
              <img src={item.icon} alt={item.title} />
            </div>
              <h3>{item.title}</h3>
              <p>
              <a href={item.link}>
                {item.desc}
                </a>
                </p>
              {/* <span className="year">{item.year}</span> */}
            </div>
          </div>
        ))

        }
      </div>
    </div> 
    </div>

                {/* <div className="container"> */}
                    {/* <Link  className="blog_item" href="/blogs/need-for-domain-privacy-protection"> */}
                    {/* <Link  className="blog_item" href="#">

                       <div className="image_1"></div>
                       
                        <p className="comment"> by Admin |   </p>
                        <p className="title">
                        Domain Privacy Protection: Why It's Essential for Website Owners
                        </p>
                    </Link> */}
                    

                    {/* <Link  className="blog_item" href="/blogs/driving-organic-traffic-strategies">
                     */}
                     {/* <Link  className="blog_item" href="#">
                        <div className="image_2"></div>
                        <p className="comment"> by Admin |   </p>
                        <p className="title">
                        Driving Organic Traffic: Essential Strategies for 2025
                        </p>
                    </Link> */}
                </div>

                {/* <div className="container"> */}

                    {/* <Link  className="blog_item" href="/blogs/blog_details"> */}
                    {/* <Link  className="blog_item" href="#">
                        <div className="image_3"></div>
                        <p className="comment"> by Admin |   </p>
                        <p className="title">
                        Website Revamping: A Strategic Approach to Business Growth
                        </p>
                    </Link> */}

                    {/* <Link  className="blog_item" href="/blogs/blog_details">
                        <div className="image"></div>
                        <p className="comment"> by Admin |   </p>
                        <p className="title">
                            Nulla facilisi. Vivamus convallis lacinia ipsum sed varius.
                            Sed eget finibus metus. Sed arcu leibero.
                        </p>
                    </Link> */}
                {/* </div> */}

            {/* </div> */}
            {/* <div className="pagination_section">
                <span className="active">1</span>
                <span>2</span>
                <span>3</span>
                <span className="next">Next</span>
            </div> */}
        </main>

            <Footer/>
        </div>
        </>
    )
}